<<<<<<< HEAD
-- Å×ÀÌºí »èÁ¦
DROP TABLE ITEMIMAGE CASCADE CONSTRAINTS;
PROMPT DROPPING ITEMIMAGE...
DROP TABLE NOTICE CASCADE CONSTRAINTS;
PROMPT DROPPING NOTICE...
DROP TABLE QNA CASCADE CONSTRAINTS;
PROMPT DROPPING QNA...
DROP TABLE REVIEW CASCADE CONSTRAINTS;
PROMPT DROPPING REVIEW...
DROP TABLE STATISTIC CASCADE CONSTRAINTS;
PROMPT DROPPING STATISTIC...
DROP TABLE WISHLIST CASCADE CONSTRAINTS;
PROMPT DROPPING WISHLIST...
DROP TABLE CARTLIST CASCADE CONSTRAINTS;
PROMPT DROPPING CARTLIST...
DROP TABLE ORDERLIST CASCADE CONSTRAINTS;
PROMPT DROPPING ORDERLIST...
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
PROMPT DROPPING PAYMENT...
DROP TABLE IMAGE CASCADE CONSTRAINTS;
PROMPT DROPPING IMAGE...
DROP TABLE ITEM CASCADE CONSTRAINTS;
PROMPT DROPPING ITEM...
DROP TABLE KEYWORD CASCADE CONSTRAINTS;
PROMPT DROPPING KEYWORD...
DROP TABLE DELIVERY CASCADE CONSTRAINTS;
PROMPT DROPPING DELIVERY...
DROP TABLE MEMBER CASCADE CONSTRAINTS;
PROMPT DROPPING MEMBER...
DROP TABLE RANK CASCADE CONSTRAINTS;
PROMPT DROPPING RANK...

-- Å×ÀÌºí Ãß°¡
PROMPT CREATING RANK...
CREATE TABLE RANK
(
	RANK_NO	NVARCHAR2(30) CONSTRAINT PK_RANK PRIMARY KEY,
	RANK_NAME NVARCHAR2(60),
	RANK_POINTRAT NUMBER,
	RANK_POINTCAP NUMBER,
	RANK_POINTMIN NUMBER,
	RANK_POINTMAX NUMBER
);

COMMENT ON COLUMN RANK.RANK_NO IS 'µî±Þ¹øÈ£(R00001~R00005)';
COMMENT ON COLUMN RANK.RANK_NAME IS 'µî±ÞÀÌ¸§(¾¾¾Ñ,»õ½Ï,°¡Áö,¿­¸Å,³ª¹«)';
COMMENT ON COLUMN RANK.RANK_POINTRAT IS 'µî±ÞÀû¸³À²(1%~5%)';
COMMENT ON COLUMN RANK.RANK_POINTCAP IS 'Æ÷ÀÎÆ®»ç¿ëÇÑµµ(2000~10000)';
COMMENT ON COLUMN RANK.RANK_POINTMIN IS 'µî±Þ¾÷ ÃÖ¼Ò ±¸¸Å±Ý¾×';
COMMENT ON COLUMN RANK.RANK_POINTMAX IS 'µî±Þ¾÷ ÃÖ´ë ±¸¸Å ±Ý¾×';

PROMPT CREATING MEMBER...
CREATE TABLE MEMBER
(
	MEMBER_NO NVARCHAR2(30) CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_ADMIN NVARCHAR2(2) DEFAULT 'N' NOT NULL CONSTRAINT CK_MEMBER_ADMIN CHECK(MEMBER_ADMIN IN('Y', 'N')),
	MEMBER_ID NVARCHAR2(30) NOT NULL CONSTRAINT UQ_MEMBER_ID UNIQUE,
	MEMBER_PWD NVARCHAR2(30),
	MEMBER_NAME	NVARCHAR2(30) NOT NULL,
	MEMBER_PHONE1 NVARCHAR2(10),
	MEMBER_PHONE2 NVARCHAR2(10),
	MEMBER_PHONE3 NVARCHAR2(10),
	MEMBER_EMAIL1 NVARCHAR2(30),
	MEMBER_EMAIL2 NVARCHAR2(30),
	MEMBER_POSTCODE	NVARCHAR2(30),
	MEMBER_ADDRESS1	NVARCHAR2(2000),
	MEMBER_ADDRESS2	NVARCHAR2(2000),
	MEMBER_JOINDATE	DATE DEFAULT SYSDATE NOT NULL,
	MEMBER_STATUS NVARCHAR2(2) DEFAULT 'N' NOT NULL CONSTRAINT CK_MEMBER_STATUS CHECK(MEMBER_STATUS IN('Y', 'N')),
	MEMBER_EXIT	NVARCHAR2(500),
	MEMBER_POINT NUMBER,
	MEMBER_RANK	NVARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN MEMBER.MEMBER_NO IS 'È¸¿ø¹øÈ£(M000001~)';
COMMENT ON COLUMN MEMBER.MEMBER_ADMIN IS '°ü¸®ÀÚ:Y, ÀÏ¹ÝÈ¸¿ø:N';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '¾ÆÀÌµð,À¯´ÏÅ©';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS 'ºñ¹Ð¹øÈ£';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS 'ÀÌ¸§';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE1 IS '¿¬¶ôÃ³1';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE2 IS '¿¬¶ôÃ³2';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE3 IS '¿¬¶ôÃ³3';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL1 IS 'ÀÌ¸ÞÀÏ1';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL2 IS 'ÀÌ¸ÞÀÏ2';
COMMENT ON COLUMN MEMBER.MEMBER_POSTCODE IS '¿ìÆí¹øÈ£';
COMMENT ON COLUMN MEMBER.MEMBER_ADDRESS1 IS 'ÁÖ¼Ò';
COMMENT ON COLUMN MEMBER.MEMBER_ADDRESS2 IS '»ó¼¼ÁÖ¼Ò';
COMMENT ON COLUMN MEMBER.MEMBER_JOINDATE IS 'È¸¿ø°¡ÀÔ³¯Â¥';
COMMENT ON COLUMN MEMBER.MEMBER_STATUS IS 'Å»Åð:Y ±âº»: N, Ä«Ä«¿À:K È¸¿ø»óÅÂ';
COMMENT ON COLUMN MEMBER.MEMBER_EXIT IS 'Å»Åð»çÀ¯';
COMMENT ON COLUMN MEMBER.MEMBER_POINT IS 'Æ÷ÀÎÆ®';
COMMENT ON COLUMN MEMBER.MEMBER_RANK IS 'µî±Þ¹øÈ£(R1~R5)';

ALTER TABLE MEMBER ADD CONSTRAINT FK_RANK_TO_MEMBER FOREIGN KEY ( MEMBER_RANK )
REFERENCES RANK ( RANK_NO );


PROMPT CREATING DELIVERY...
CREATE TABLE DELIVERY
(
	DELIVERY_CODE NVARCHAR2(30) DEFAULT 'D1' CONSTRAINT PK_DELIVERY PRIMARY KEY,
	DELIVERY_STATUS	NVARCHAR2(100)
);

COMMENT ON COLUMN DELIVERY.DELIVERY_CODE IS 'D1 : ¹è¼ÛÀü, D2 : ¹è¼ÛÁß, D3 : ¹è¼Û¿Ï·á(¹è¼ÛÄÚµå)';
COMMENT ON COLUMN DELIVERY.DELIVERY_STATUS IS '¹è¼ÛÀü, ¹è¼ÛÁß, ¹è¼Û¿Ï·á(¹è¼Û»óÅÂ)';

PROMPT CREATING KEYWORD...
CREATE TABLE KEYWORD (
	KEYWORD_NO NVARCHAR2(30) CONSTRAINT PK_KEYWORD PRIMARY KEY,
	KEYWORD_NAME NVARCHAR2(20)
);

COMMENT ON COLUMN KEYWORD.KEYWORD_NO IS 'Å°¿öµå¹øÈ£(K1~)';
COMMENT ON COLUMN KEYWORD.KEYWORD_NAME IS 'Áßº¹ ¼±ÅÃ(»ê¼Ò»Õ»Õ, ¹Ý·Áµ¿¹° Ä£È­)';


PROMPT CREATING ITEM...
CREATE TABLE ITEM 
(	
ITEM_NO NVARCHAR2(30) CONSTRAINT PK_ITEM PRIMARY KEY, 
ITEM_NAME NVARCHAR2(50) NOT NULL, 
ITEM_CATEGORY NVARCHAR2(2000) NOT NULL, 
KEYWORD_NO NVARCHAR2(30) NOT NULL, 
ITEM_PRICE NUMBER NOT NULL, 
ITEM_DISCOUNT NUMBER NOT NULL, 
ITEM_RATE NUMBER, 
ITEM_STOCK NUMBER NOT NULL, 
ITEM_DISPLAY NVARCHAR2(2) DEFAULT 'N' NOT NULL CONSTRAINT CK_ITEM_DISPLAY CHECK(ITEM_DISPLAY IN('Y', 'N')), 
ITEM_INFO NVARCHAR2(2000) NOT NULL, 
ITEM_CDATE DATE DEFAULT SYSDATE NOT NULL, 
ITEM_UDATE DATE DEFAULT SYSDATE NOT NULL, 
ITEM_SCOUNT NUMBER, 
ITEM_MAX NUMBER NOT NULL, 
ITEM_SALE NVARCHAR2(2) DEFAULT 'Y' CONSTRAINT CK_ITEM_SALE CHECK(ITEM_SALE IN('Y', 'N'))
);

COMMENT ON COLUMN ITEM.ITEM_NO IS '»óÇ°¹øÈ£(I00001~)';
COMMENT ON COLUMN ITEM.ITEM_NAME IS '»óÇ°¸í';
COMMENT ON COLUMN ITEM.ITEM_CATEGORY IS '»óÇ°Ä«Å×°í¸®';
COMMENT ON COLUMN ITEM.KEYWORD_NO IS 'Å°¿öµå¹øÈ£(K1~)';
COMMENT ON COLUMN ITEM.ITEM_PRICE IS '»óÇ°°¡°Ý';
COMMENT ON COLUMN ITEM.ITEM_DISCOUNT IS 'ÇÒÀÎ°ª';
COMMENT ON COLUMN ITEM.ITEM_RATE IS 'ÆòÁ¡';
COMMENT ON COLUMN ITEM.ITEM_STOCK IS '»óÇ°Àç°í';
COMMENT ON COLUMN ITEM.ITEM_DISPLAY IS 'Àü½Ã : Y, ºñÀü½Ã : N';
COMMENT ON COLUMN ITEM.ITEM_INFO IS '»óÇ°¼³¸íÅØ½ºÆ®';
COMMENT ON COLUMN ITEM.ITEM_CDATE IS '»óÇ°µî·ÏÀÏ';
COMMENT ON COLUMN ITEM.ITEM_UDATE IS 'ÃÖÁ¾¼öÁ¤ÀÏ';
COMMENT ON COLUMN ITEM.ITEM_SCOUNT IS '´©ÀûÆÇ¸Å·®';
COMMENT ON COLUMN ITEM.ITEM_MAX IS 'ÃÖ´ë±¸¸Å¼ö·®';
COMMENT ON COLUMN ITEM.ITEM_SALE IS 'ÆÇ¸ÅÁß : Y, ÆÇ¸ÅÁßÁö : N';

ALTER TABLE item ADD CONSTRAINT FK_keyword_TO_item FOREIGN KEY ( keyword_no )
REFERENCES keyword ( keyword_no );


PROMPT CREATING IMAGE...
CREATE TABLE IMAGE 
(
	IMAGE_NO NVARCHAR2(30) CONSTRAINT PK_IMAGE PRIMARY KEY,
	IMAGE_PATH NVARCHAR2(2000),
	IMAGE_NAME NVARCHAR2(2000)
);

COMMENT ON COLUMN IMAGE.IMAGE_NO IS 'ÀÌ¹ÌÁö¹øÈ£(IMG00001~)';
COMMENT ON COLUMN IMAGE.IMAGE_PATH IS 'ÀÌ¹ÌÁö °æ·Î';
COMMENT ON COLUMN IMAGE.IMAGE_NAME IS 'ÀÌ¹ÌÁö ¸íÄª';


PROMPT CREATING PAYMENT...
CREATE TABLE PAYMENT 
(
	PAYMENT_CODE NVARCHAR2(30) DEFAULT 'P1' CONSTRAINT PK_PAYMENT PRIMARY KEY,
	PAYMENT_STATUS NVARCHAR2(100)
);

COMMENT ON COLUMN PAYMENT.PAYMENT_CODE IS 'P1 : ÀÔ±Ý Àü, P2 : ÀÔ±Ý ÈÄ(ÀÔ±ÝÄÚµå)';
COMMENT ON COLUMN PAYMENT.PAYMENT_STATUS IS 'ÀÔ±Ý Àü, ÀÔ±Ý ÈÄ(ÀÔ±Ý»óÅÂ)';


PROMPT CREATING ORDERLIST...
CREATE TABLE ORDERLIST 
(
	ORDER_NO NVARCHAR2(30),
	ITEM_NO	NVARCHAR2(30),
	MEMBER_NO NVARCHAR2(30) NOT NULL,
	ORDER_DATE DATE DEFAULT SYSDATE NOT NULL,
	ORDER_COUNT	NUMBER NOT NULL,
	ORDER_USEPOINT	NUMBER NOT NULL,
	ORDER_NAME	NVARCHAR2(100) NOT NULL,
	ORDER_PHONE1 NVARCHAR2(10) NOT NULL,
	ORDER_PHONE2 NVARCHAR2(10) NOT NULL,
	ORDER_PHONE3 NVARCHAR2(10) NOT NULL,
	ORDER_POSTCODE NVARCHAR2(30) NOT NULL,
	ORDER_ADDRESS1 NVARCHAR2(2000) NOT NULL,
	ORDER_ADDRESS2 NVARCHAR2(2000) NOT NULL,
	ORDER_REQUEST NVARCHAR2(2000),
	ORDER_DCOST	NUMBER NOT NULL,
	ORDER_CANCELREQUEST	NVARCHAR2(2) DEFAULT 'N' CONSTRAINT CK_ORDER_CANCELREQUEST CHECK(ORDER_CANCELREQUEST IN('Y', 'N')),
	ORDER_CANCELYN NVARCHAR2(2) DEFAULT 'N' CONSTRAINT CK_ORDER_CANCELYN CHECK(ORDER_CANCELYN IN('Y', 'N')),
	DELIVERY_CODE NVARCHAR2(10) NOT NULL,
	PAYMENT_CODE NVARCHAR2(10) DEFAULT 'P1' NOT NULL
);

ALTER TABLE ORDERLIST ADD CONSTRAINT PK_ORDERLIST PRIMARY KEY (
	ORDER_NO,
	ITEM_NO
);

ALTER TABLE ORDERLIST ADD CONSTRAINT FK_ITEM_TO_ORDERLIST FOREIGN KEY ( ITEM_NO )
REFERENCES ITEM ( ITEM_NO );
ALTER TABLE ORDERLIST ADD CONSTRAINT FK_MEMBER_TO_ORDERLIST FOREIGN KEY ( MEMBER_NO )
REFERENCES MEMBER (	MEMBER_NO );
ALTER TABLE ORDERLIST ADD CONSTRAINT FK_DELIVERY_TO_ORDERLIST FOREIGN KEY ( DELIVERY_CODE )
REFERENCES DELIVERY ( DELIVERY_CODE );
ALTER TABLE ORDERLIST ADD CONSTRAINT FK_PAYMENT_TO_ORDERLIST FOREIGN KEY ( PAYMENT_CODE )
REFERENCES PAYMENT ( PAYMENT_CODE );


COMMENT ON COLUMN ORDERLIST.ORDER_NO IS 'ÁÖ¹®¹øÈ£(O00001~ )';
COMMENT ON COLUMN ORDERLIST.ITEM_NO IS '»óÇ°¹øÈ£(I1~)';
COMMENT ON COLUMN ORDERLIST.MEMBER_NO IS 'È¸¿ø¹øÈ£(M1~)';
COMMENT ON COLUMN ORDERLIST.ORDER_DATE IS 'ÁÖ¹®ÀÏ½Ã';
COMMENT ON COLUMN ORDERLIST.ORDER_COUNT IS 'ÁÖ¹®¼ö·®';
COMMENT ON COLUMN ORDERLIST.ORDER_USEPOINT IS '»ç¿ëÆ÷ÀÎÆ®';
COMMENT ON COLUMN ORDERLIST.ORDER_NAME IS '¼ö·ÉÀÚÀÌ¸§';
COMMENT ON COLUMN ORDERLIST.ORDER_PHONE1 IS '¼ö·ÉÀÚÀüÈ­¹øÈ£1';
COMMENT ON COLUMN ORDERLIST.ORDER_PHONE2 IS '¼ö·ÉÀÚÀüÈ­¹øÈ£2';
COMMENT ON COLUMN ORDERLIST.ORDER_PHONE3 IS '¼ö·ÉÀÚÀüÈ­¹øÈ£3';
COMMENT ON COLUMN ORDERLIST.ORDER_POSTCODE IS '¼ö·ÉÀÚ¿ìÆí¹øÈ£';
COMMENT ON COLUMN ORDERLIST.ORDER_ADDRESS1 IS '¼ö·ÉÀÚÁÖ¼Ò';
COMMENT ON COLUMN ORDERLIST.ORDER_ADDRESS2 IS '¼ö·ÉÀÚ»ó¼¼ÁÖ¼Ò';
COMMENT ON COLUMN ORDERLIST.ORDER_REQUEST IS '¹è¼Û½Ã¿äÃ»»çÇ×';
COMMENT ON COLUMN ORDERLIST.ORDER_DCOST IS '¹è¼Ûºñ';
COMMENT ON COLUMN ORDERLIST.ORDER_CANCELREQUEST IS '±âº»: N , Ãë¼Ò : Y';
COMMENT ON COLUMN ORDERLIST.ORDER_CANCELYN IS '±âº»: N , ½ÂÀÎ : Y (ÁÖ¹® »èÁ¦ È¿°ú)';
COMMENT ON COLUMN ORDERLIST.DELIVERY_CODE IS 'D1 : ¹è¼ÛÀü, D2 : ¹è¼ÛÁß, D3 : ¹è¼Û¿Ï·á';
COMMENT ON COLUMN ORDERLIST.PAYMENT_CODE IS 'P1 : ÀÔ±Ý Àü, P2 : ÀÔ±Ý ÈÄ';


PROMPT CREATING CARTLIST...
CREATE TABLE CARTLIST 
(
	CARTLIST_NO	NVARCHAR2(30) CONSTRAINT PK_CARTLIST PRIMARY KEY,
	ITEM_NO NVARCHAR2(30) NOT NULL,
	MEMBER_NO NVARCHAR2(30) NOT NULL,
	CARTLIST_COUNT NUMBER
);

ALTER TABLE CARTLIST ADD CONSTRAINT FK_ITEM_TO_CARTLIST FOREIGN KEY ( ITEM_NO )
REFERENCES ITEM ( ITEM_NO );

ALTER TABLE CARTLIST ADD CONSTRAINT FK_MEMBER_TO_CARTLIST FOREIGN KEY ( MEMBER_NO )
REFERENCES MEMBER ( MEMBER_NO );

COMMENT ON COLUMN CARTLIST.CARTLIST_NO IS 'Àå¹Ù±¸´Ï¹øÈ£(C00001~)';
COMMENT ON COLUMN CARTLIST.ITEM_NO IS '»óÇ°¹øÈ£';
COMMENT ON COLUMN CARTLIST.MEMBER_NO IS 'È¸¿ø¹øÈ£(M1~)';
COMMENT ON COLUMN CARTLIST.CARTLIST_COUNT IS '¼ö·®';


PROMPT CREATING CARTLIST...
CREATE TABLE WISHLIST 
(
	WISHLIST_NO	NVARCHAR2(30) CONSTRAINT PK_WISHLIST PRIMARY KEY,
	ITEM_NO	NVARCHAR2(30) NOT NULL,
	MEMBER_NO NVARCHAR2(30) NOT NULL,
	WISHLIST_MEMO NVARCHAR2(500)
);

ALTER TABLE WISHLIST ADD CONSTRAINT FK_ITEM_TO_WISHLIST FOREIGN KEY ( ITEM_NO )
REFERENCES ITEM ( ITEM_NO );
ALTER TABLE WISHLIST ADD CONSTRAINT FK_MEMBER_TO_WISHLIST FOREIGN KEY ( MEMBER_NO )
REFERENCES MEMBER ( MEMBER_NO );

COMMENT ON COLUMN WISHLIST.WISHLIST_NO IS 'À§½Ã¸®½ºÆ®¹øÈ£(W00001~)';
COMMENT ON COLUMN WISHLIST.ITEM_NO IS '»óÇ°¹øÈ£';
COMMENT ON COLUMN WISHLIST.MEMBER_NO IS 'È¸¿ø¹øÈ£(M1~)';
COMMENT ON COLUMN WISHLIST.WISHLIST_MEMO IS '¸Þ¸ð';


PROMPT CREATING STATISTIC...
CREATE TABLE STATISTIC 
(
	STATISTIC_NO NVARCHAR2(30) CONSTRAINT PK_STATISTIC PRIMARY KEY,
	STATISTIC_VISITCOUNT NUMBER,
	STATISTIC_TODAYJOIN NUMBER,
	STATISTIC_CANCELCOUNT NUMBER,
	STATISTIC_MEMBER NUMBER,
	STATISTIC_DASK NUMBER,
	STATISTIC_IASK NUMBER,
	STATISTIC_CASK NUMBER,
	STATISTIC_SALES NUMBER,
	STATISTIC_DBEFORE NUMBER,
	STATISTIC_NEWORDER NUMBER,
	STATISTIC_CDATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN STATISTIC.STATISTIC_NO IS 'ÀÏÀÏÅë°è(sta00001-)';
COMMENT ON COLUMN STATISTIC.STATISTIC_VISITCOUNT IS '¹æ¹®ÀÚ¼ö';
COMMENT ON COLUMN STATISTIC.STATISTIC_TODAYJOIN IS '±ÝÀÏ°¡ÀÔ';
COMMENT ON COLUMN STATISTIC.STATISTIC_CANCELCOUNT IS 'Ãë¼Ò¿äÃ»';
COMMENT ON COLUMN STATISTIC.STATISTIC_MEMBER IS 'ÀüÃ¼È¸¿ø';
COMMENT ON COLUMN STATISTIC.STATISTIC_DASK IS '¹è¼Û¹®ÀÇ';
COMMENT ON COLUMN STATISTIC.STATISTIC_IASK IS '»óÇ°¹®ÀÇ';
COMMENT ON COLUMN STATISTIC.STATISTIC_CASK IS 'Ãë¼Ò¹®ÀÇ';
COMMENT ON COLUMN STATISTIC.STATISTIC_SALES IS '±ÝÀÏ¸ÅÃâ';
COMMENT ON COLUMN STATISTIC.STATISTIC_DBEFORE IS '¹è¼Û´ë±â';
COMMENT ON COLUMN STATISTIC.STATISTIC_NEWORDER IS '½Å±ÔÁÖ¹®';
COMMENT ON COLUMN STATISTIC.STATISTIC_CDATE IS 'µî·ÏÀÏ';


PROMPT CREATING REVIEW...
CREATE TABLE REVIEW 
(
	REVIEW_NO NVARCHAR2(30) CONSTRAINT PK_REVIEW PRIMARY KEY,
	ORDER_NO NVARCHAR2(30) NOT NULL,
	ITEM_NO	NVARCHAR2(30) NOT NULL,
	MEMBER_NO NVARCHAR2(30) NOT NULL,
	REVIEW_CDATE DATE DEFAULT SYSDATE,
	REVIEW_RATE	NUMBER,
	REVIEW_CONTENT NVARCHAR2(2000),
	REVIEW_UDATE DATE DEFAULT SYSDATE,
	REVIEW_IMAGENAME NVARCHAR2(2000),
    REVIEW_IMAGEPATH NVARCHAR2(2000)
);

ALTER TABLE REVIEW ADD CONSTRAINT FK_ORDERLIST_TO_REVIEW FOREIGN KEY ( ORDER_NO, ITEM_NO )
REFERENCES ORDERLIST ( ORDER_NO, ITEM_NO );
ALTER TABLE REVIEW ADD CONSTRAINT FK_MEMBER_TO_REVIEW FOREIGN KEY ( MEMBER_NO )
REFERENCES MEMBER ( MEMBER_NO );

COMMENT ON COLUMN REVIEW.REVIEW_NO IS '¸®ºä¹øÈ£(R00001~ )';
COMMENT ON COLUMN REVIEW.ORDER_NO IS 'ÁÖ¹®¹øÈ£(O00001~ )';
COMMENT ON COLUMN REVIEW.ITEM_NO IS '»óÇ°¹øÈ£(I00001~ )';
COMMENT ON COLUMN REVIEW.MEMBER_NO IS 'È¸¿ø¹øÈ£';
COMMENT ON COLUMN REVIEW.REVIEW_CDATE IS '¸®ºäµî·ÏÀÏ';
COMMENT ON COLUMN REVIEW.REVIEW_RATE IS 'ÆòÁ¡';
COMMENT ON COLUMN REVIEW.REVIEW_CONTENT IS '¸®ºä³»¿ë';
COMMENT ON COLUMN REVIEW.REVIEW_UDATE IS '¸®ºä¼öÁ¤ÀÏ';
COMMENT ON COLUMN REVIEW.REVIEW_IMAGENAME IS 'ÀÌ¹ÌÁöÀÌ¸§';
COMMENT ON COLUMN REVIEW.REVIEW_IMAGEPATH IS 'ÀÌ¹ÌÁö°æ·Î';


PROMPT CREATING QNA...
CREATE TABLE QNA 
(
	QNA_NO NVARCHAR2(30) CONSTRAINT PK_QNA PRIMARY KEY,
	MEMBER_NO NVARCHAR2(30) NOT NULL,
	QNA_TITLE NVARCHAR2(100) NOT NULL,
	QNA_CDATE DATE,
	QNA_CONTENT	NVARCHAR2(2000),
	QNA_ANSWER NVARCHAR2(2000),
	QNA_CATEGORY NVARCHAR2(20) NOT NULL,
    QNA_PASSWORD NVARCHAR2(20) NOT NULL,
	QNA_YN NVARCHAR2(2) DEFAULT 'N' CONSTRAINT CK_QNA_YN CHECK(QNA_YN IN('Y', 'N')),
	QNA_IMAGENAME NVARCHAR2(2000),
    QNA_IMAGEPATH NVARCHAR2(2000)
);

ALTER TABLE QNA ADD CONSTRAINT FK_MEMBER_TO_QNA FOREIGN KEY ( MEMBER_NO )
REFERENCES MEMBER ( MEMBER_NO );

COMMENT ON COLUMN QNA.QNA_NO IS '±Û¹øÈ£(Q00001~)';
COMMENT ON COLUMN QNA.MEMBER_NO IS 'È¸¿ø¹øÈ£(M1~)';
COMMENT ON COLUMN QNA.QNA_TITLE IS 'Áú¹®Á¦¸ñ';
COMMENT ON COLUMN QNA.QNA_CDATE IS '°Ô½ÃÀÏ';
COMMENT ON COLUMN QNA.QNA_CONTENT IS '³»¿ë';
COMMENT ON COLUMN QNA.QNA_ANSWER IS '´äº¯';
COMMENT ON COLUMN QNA.QNA_CATEGORY IS 'ºÐ·ù';
COMMENT ON COLUMN QNA.QNA_PASSWORD IS 'ºñ¹Ð¹øÈ£';
COMMENT ON COLUMN QNA.QNA_YN IS '´äº¯ Àü : N, ´äº¯ : Y';
COMMENT ON COLUMN QNA.QNA_IMAGENAME IS 'ÀÌ¹ÌÁöÀÌ¸§';
COMMENT ON COLUMN QNA.QNA_IMAGEPATH IS 'ÀÌ¹ÌÁö°æ·Î';


PROMPT CREATING NOTICE...
CREATE TABLE NOTICE (
	NOTICE_NO NVARCHAR2(30) CONSTRAINT PK_NOTICE PRIMARY KEY,
	MEMBER_NO NVARCHAR2(30) NOT NULL,
	NOTICE_TITLE NVARCHAR2(100) NOT NULL,
	NOTICE_CDATE DATE,
	NOTICE_CONTENT NVARCHAR2(2000),
    NOTICE_IMAGENAME NVARCHAR2(2000),
    NOTICE_IMAGEPATH NVARCHAR2(2000)
);

ALTER TABLE NOTICE ADD CONSTRAINT FK_MEMBER_TO_NOTICE FOREIGN KEY ( MEMBER_NO )
REFERENCES MEMBER ( MEMBER_NO );

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '°øÁö±Û¹øÈ£(N00001~)';
COMMENT ON COLUMN NOTICE.MEMBER_NO IS 'È¸¿ø¹øÈ£(M00001~)';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS 'Á¦¸ñ';
COMMENT ON COLUMN NOTICE.NOTICE_CDATE IS '°Ô½ÃÀÏ';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '³»¿ë';
COMMENT ON COLUMN NOTICE.NOTICE_IMAGENAME IS 'ÀÌ¹ÌÁöÀÌ¸§';
COMMENT ON COLUMN NOTICE.NOTICE_IMAGEPATH IS 'ÀÌ¹ÌÁö°æ·Î';


PROMPT CREATING ITEMIMAGE...
CREATE TABLE ITEMIMAGE (
    ITEMIMAGE_NO NVARCHAR2(30) CONSTRAINT PK_ITEMIMAGE PRIMARY KEY,
    ITEM_NO   NVARCHAR2(30),
    IMAGE_NO NVARCHAR2(30),
    ITEMIMAGE_CATEGORY NUMBER
);

ALTER TABLE ITEMIMAGE ADD CONSTRAINT FK_ITEM_TO_ITEMIMAGE FOREIGN KEY ( ITEM_NO )
REFERENCES ITEM ( ITEM_NO );
ALTER TABLE ITEMIMAGE ADD CONSTRAINT FK_IMAGE_TO_ITEMIMAGE FOREIGN KEY ( IMAGE_NO )
REFERENCES IMAGE ( IMAGE_NO );

COMMENT ON COLUMN ITEMIMAGE.ITEMIMAGE_NO IS '»óÇ°ÀÌ¹ÌÁö¹øÈ£(Ii00001~)';
COMMENT ON COLUMN ITEMIMAGE.ITEM_NO IS '»óÇ°¹øÈ£(I00001~)';
COMMENT ON COLUMN ITEMIMAGE.IMAGE_NO IS 'ÀÌ¹ÌÁö¹øÈ£(img00001~)';
COMMENT ON COLUMN ITEMIMAGE.ITEMIMAGE_CATEGORY IS '¸ÞÀÎÀÌ¹ÌÁö:1,¼­ºêÀÌ¹ÌÁö:2';

--------------------------------------------------------
-- DDL for Sequence IMAGE_SEQ
DROP SEQUENCE IMAGE_SEQ;
DROP SEQUENCE ITEMIMAGE_SEQ;
DROP SEQUENCE ITEM_SEQ;
DROP SEQUENCE MNO_SEQ;

CREATE SEQUENCE  IMAGE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 
START WITH 24 
CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE ITEMIMAGE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 
START WITH 25 
CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE ITEM_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 
START WITH 23 
CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE  MNO_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 
START WITH 8
CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------

-- µ¥ÀÌÅÍ Ãß°¡
REM INSERTING into ONECHO.RANK
SET DEFINE OFF;
Insert into ONECHO.RANK (RANK_NO,RANK_NAME,RANK_POINTRAT,RANK_POINTCAP,RANK_POINTMIN,RANK_POINTMAX) values ('R1','¾¾¾Ñ',1,2000,0,50000);
Insert into ONECHO.RANK (RANK_NO,RANK_NAME,RANK_POINTRAT,RANK_POINTCAP,RANK_POINTMIN,RANK_POINTMAX) values ('R2','»õ½Ï',2,4000,50001,200000);
Insert into ONECHO.RANK (RANK_NO,RANK_NAME,RANK_POINTRAT,RANK_POINTCAP,RANK_POINTMIN,RANK_POINTMAX) values ('R3','°¡Áö',3,6000,200001,500000);
Insert into ONECHO.RANK (RANK_NO,RANK_NAME,RANK_POINTRAT,RANK_POINTCAP,RANK_POINTMIN,RANK_POINTMAX) values ('R4','¿­¸Å',4,8000,500001,1000000);
Insert into ONECHO.RANK (RANK_NO,RANK_NAME,RANK_POINTRAT,RANK_POINTCAP,RANK_POINTMIN,RANK_POINTMAX) values ('R5','³ª¹«',5,10000,1000001,999999999);

REM INSERTING into ONECHO.MEMBER
SET DEFINE OFF;
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK) 
values ('M00001','Y','admin1','admin1','Á¤À¯Áø','010','1234','5678','admin1','@oncho.com','12345','2','2',to_date('20/06/02','RR/MM/DD'),'N',null,2000,'R2');
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK) 
values ('M00002','Y','admin2','admin2','°­±¤»ê','010','1234','5678','admin2','@oncho.com','12345','2','2',to_date('20/06/02','RR/MM/DD'),'N',null,4000,'R2');
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK) 
values ('M00003','Y','admin3','admin3','ÀÌ¾Æ¶ó','010','1234','5678','admin3','@oncho.com','12345','3','3',to_date('20/06/02','RR/MM/DD'),'N',null,8000,'R3');
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK)
values ('M00004','Y','admin4','admin4','±è°æ³²','010','1234','5678','admin4','@oncho.com','12345','4','4',to_date('20/06/02','RR/MM/DD'),'N',null,12000,'R4');
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK)
values ('M00005','Y','admin5','admin5','ÀÌ¼öÇÑ','010','1234','5678','admin5','@oncho.com','12345','5','5',to_date('20/06/02','RR/MM/DD'),'N',null,16000,'R5');
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK)
values ('M00006','N','user1','user1','È«±æµ¿','010','2828','8282','user1','@naver.com','06234','¼­¿ïÆ¯º°½Ã °­³²±¸ Å×Çì¶õ·Î14±æ 6 (¿ª»ïµ¿)','2Ãþ',to_date('20/06/02','RR/MM/DD'),'N',null,2000,'R1');
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK)
values ('M00007','N','user2','user2','È«±æ³²','010','7568','5678','user2','@gmail.com','06234','¼­¿ïÆ¯º°½Ã °­³²±¸ Å×Çì¶õ·Î14±æ 6 (¿ª»ïµ¿)','3Ãþ',to_date('20/06/03','RR/MM/DD'),'N',null,9000,'R2');

REM INSERTING into ONECHO.KEYWORD
SET DEFINE OFF;
Insert into ONECHO.KEYWORD (KEYWORD_NO,KEYWORD_NAME) values ('K1','»ê¼Ò»Õ»Õ');
Insert into ONECHO.KEYWORD (KEYWORD_NO,KEYWORD_NAME) values ('K2','¹Ý·Áµ¿¹° Ä£È­');
Insert into ONECHO.KEYWORD (KEYWORD_NO,KEYWORD_NAME) values ('K3','»ê¼Ò»Õ»Õ ¹Ý·Áµ¿¹° Ä£È­');

REM INSERTING into ONECHO.IMAGE
SET DEFINE OFF;
Insert into ONECHO.IMAGE (IMAGE_NO,IMAGE_PATH,IMAGE_NAME) values ('IMG00001','/IMAGES/ITEM/','°í¹«³ª¹«.jpg');
Insert into ONECHO.IMAGE (IMAGE_NO,IMAGE_PATH,IMAGE_NAME) values ('IMG00002','/IMAGES/ITEM/','smim.jpg');
Insert into ONECHO.IMAGE (IMAGE_NO,IMAGE_PATH,IMAGE_NAME) values ('IMG00003','/IMAGES/ITEM/','testsample.jpg');
Insert into ONECHO.IMAGE (IMAGE_NO,IMAGE_PATH,IMAGE_NAME) values ('IMG00004','/IMAGES/ITEM/','testsample.jpg');

REM INSERTING into ONECHO.ITEM
SET DEFINE OFF;
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00001','¾ßÀÚ¼ö¿°Æ¿¶õµå½Ã¾Æ','HANGING','K3',26500,25000,0,28,'Y','Áý¿¡ ½Ì±×·¯¿òÀ» ´õÇØÁÙ »Ó ¾Æ´Ï¶ó °ø±âÁ¤È­ ´É·Âµµ ¶Ù¾î³­ ¾ßÀÚ¼ö¿°Æ¿¶õµå½Ã¾Æ',to_date('20/05/21','RR/MM/DD'),to_date('20/05/21','RR/MM/DD'),13,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00002','¹®»þÀÎ','SOIL','K1',25000,24000,0,34,'Y','ÀÌ¸§ ±×´ë·Î ´ÞºûÀ» ¸Ó±ÝÀºµíÇÑ ¿À¹¦ÇÑ »öÀÌ ¸Å·ÂÀûÀÎ ¹®»þÀÎ',to_date('20/05/22','RR/MM/DD'),to_date('20/05/22','RR/MM/DD'),8,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00003','¸ó½ºÅ×¶ó','SOIL','K1',27000,26000,0,21,'Y','³ÐÀº ÀÙÀÌ ÁÖ´Â ÀÌ±¹ÀûÀÎ ºÐÀ§±â¸¦ ³»´Â ¸ó½ºÅ×¶ó',to_date('20/05/23','RR/MM/DD'),to_date('20/05/23','RR/MM/DD'),1,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00004','µð½Ãµð¾Æ','HANGING','K3',19500,17000,0,15,'Y','µ¿±Ûµ¿±ÛÇÑ ÀÔ»ç±Í¿¡ Èò»ö Å×µÎ¸®°¡ ¸Å·ÂÀûÀÎ µð½Ãµð¾Æ',to_date('20/05/24','RR/MM/DD'),to_date('20/05/24','RR/MM/DD'),1,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00005','¶óÅºÆ÷·¹½ºÆ®','SOIL','K1',28900,26900,0,19,'Y','½ºÆÄÆ¼ÇÊ¸§°ú ½º³ë¿ì»çÆÄÀÌ¾î°¡ ¶óÅº¹Ù±¸´Ï¿¡ ´ã°Ü ÀÌ±¹ÀûÀÎ ºÐÀ§±â¸¦ ¾÷ ',to_date('20/05/25','RR/MM/DD'),to_date('20/05/25','RR/MM/DD'),2,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00006','½ºÆÄÆ¼ÇÊ¸§','WATER','K1',22000,21000,0,31,'Y','»ç°èÀý ³»³» ¾Æ¸§´Ù¿î ²É°ú ÇÔ²²ÇÏ´Â Áñ°Å¿ò ½ºÆÄÆ¼ÇÊ¸§',to_date('20/05/26','RR/MM/DD'),to_date('20/05/26','RR/MM/DD'),3,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00007','Çà¿î¸ñ','WATER','K1',20000,17000,0,28,'Y','ÀÌ»êÈ­Åº¼Ò, Æ÷¸§¾Ëµ¥È÷µå, º¥Á¨ µîÀÇ À¯ÇØ¹°ÁúÀ» ¸ðµÎ Èí¼öÇØÁÖ´Â Çà¿î¸ñ',to_date('20/05/27','RR/MM/DD'),to_date('20/05/27','RR/MM/DD'),1,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00008','»ê¼¼º£¸®¾Æ','SOIL','K1',23500,22500,0,21,'Y','»ç¸·¿¡ ÀÖ´Â ¼±ÀÎÀå, »ý¸í·Â ¿ÕÀÌ¶ó ºÒ¸®´Â »ê¼¼º£¸®¾Æ',to_date('20/05/28','RR/MM/DD'),to_date('20/05/28','RR/MM/DD'),1,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00009','Æ¿¶õÅ×¶ó¸®¿ò','SOIL','K3',24500,23000,0,55,'Y','Áö±¸»ó¿¡¼­ °¡Àå °­·ÂÇÑ °ø±âÃ»Á¤±â Æ¿¶õµå½Ã¾Æ',to_date('20/05/29','RR/MM/DD'),to_date('20/05/29','RR/MM/DD'),2,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00010','½ºÅ²´ä¼­½º','WATER','K1',15000,14000,0,43,'Y','È¯°æÀûÀÀ·ÂÀÌ ¶Ù¾î³ª ¹Ý·Á½Ä¹° ÃÊº¸ÀÚµµ Ä£±¸°¡ µÉ ¼ö ÀÖ´Â ½ºÅ²´ä¼­½º',to_date('20/05/30','RR/MM/DD'),to_date('20/05/30','RR/MM/DD'),3,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00011','¼ö°æ¸ó½ºÅ×¶ó','WATER','K1',27000,24000,0,5,'Y','Á¤È­´É·ÂÀÌ ¶Ù¾î³ª »õ ÁýÀÌ³ª »ç¹«½Ç¿¡¼­ °¢±¤¹Þ´Â ¼ö°æ¸ó½ºÅ×¶ó',to_date('20/05/31','RR/MM/DD'),to_date('20/05/31','RR/MM/DD'),5,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00012','Å×ÀÌºí¾ßÀÚ','WATER','K3',22500,19500,0,7,'Y','°ø±âÁ¤È­´Â ¹°·Ð °¡½ÀÈ¿°ú±îÁö Å¹¿ùÇÑ Å×ÀÌºí¾ßÀÚ',to_date('20/06/01','RR/MM/DD'),to_date('20/06/01','RR/MM/DD'),2,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00013','½º³ë¿ì»çÆÄÀÌ¾î','WATER','K1',28000,27000,0,9,'Y','ºÎ¿Í Çà¿îÀ» °¡Á®´ÙÁØ´Ù´Â ½º³ë¿ì»çÆÄÀÌ¾î',to_date('20/06/02','RR/MM/DD'),to_date('20/06/02','RR/MM/DD'),7,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00014','ÀÌ¿À³­»ç','HANGING','K3',20000,16500,0,30,'Y','Å©±â´Â ÀÛÁö¸¸ °ø±â¸¦ Á¤È­½ÃÄÑÁÖ´Â ÀÌ¿À³­»ç',to_date('20/06/03','RR/MM/DD'),to_date('20/06/03','RR/MM/DD'),3,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00015','ÇÊ·¹¾ÆÆäÆä','WATER','K3',30000,26000,0,9,'Y','±Í¿©¿î ºñÁÖ¾ó¿¡ °É¸Â´Â ±Í¿©¿î ÀÌ¸§, ÇÊ·¹¾ÆÆäÆä',to_date('20/06/04','RR/MM/DD'),to_date('20/06/04','RR/MM/DD'),5,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00016','½ºÅõÅ°','SOIL','K1',21500,19500,0,11,'Y','¹Ì±¹ NASA¿¡¼­µµ ÀÎÁõÇÑ °ø±âÁ¤È­ ´É·ÂÀ» °¡Áø ½ºÅõÅ°',to_date('20/06/05','RR/MM/DD'),to_date('20/06/05','RR/MM/DD'),20,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00017','¸¶¸®¸ð','WATER','K2',25000,22500,0,20,'Y','±âºÐÀÌ ÁÁÀ»¶© ¹° À§¸¦ µÕµÕ, º¸±â¸¸ ÇØµµ Çàº¹ÇØÁö´Â ±Í¿©¿î ¸¶¸®¸ð',to_date('20/06/06','RR/MM/DD'),to_date('20/06/06','RR/MM/DD'),19,10,'Y');


REM INSERTING into ONECHO.ITEMIMAGE
SET DEFINE OFF;
Insert into ONECHO.ITEMIMAGE (ITEMIMAGE_NO,ITEM_NO,IMAGE_NO,ITEMIMAGE_CATEGORY) values ('II00001','I00001','IMG00001',1);
Insert into ONECHO.ITEMIMAGE (ITEMIMAGE_NO,ITEM_NO,IMAGE_NO,ITEMIMAGE_CATEGORY) values ('II00002','I00001','IMG00002',2);
Insert into ONECHO.ITEMIMAGE (ITEMIMAGE_NO,ITEM_NO,IMAGE_NO,ITEMIMAGE_CATEGORY) values ('II00003','I00002','IMG00003',1);
Insert into ONECHO.ITEMIMAGE (ITEMIMAGE_NO,ITEM_NO,IMAGE_NO,ITEMIMAGE_CATEGORY) values ('II00004','I00002','IMG00002',2);
Insert into ONECHO.ITEMIMAGE (ITEMIMAGE_NO,ITEM_NO,IMAGE_NO,ITEMIMAGE_CATEGORY) values ('II00005','I00003','IMG00004',1);
Insert into ONECHO.ITEMIMAGE (ITEMIMAGE_NO,ITEM_NO,IMAGE_NO,ITEMIMAGE_CATEGORY) values ('II00006','I00003','IMG00005',2);

REM INSERTING into ONECHO.CARTLIST
SET DEFINE OFF;
Insert into ONECHO.CARTLIST (CARTLIST_NO,ITEM_NO,MEMBER_NO,CARTLIST_COUNT) values ('C00001','I00001','M00007',3);
Insert into ONECHO.CARTLIST (CARTLIST_NO,ITEM_NO,MEMBER_NO,CARTLIST_COUNT) values ('C00004','I00002','M00007',1);
Insert into ONECHO.CARTLIST (CARTLIST_NO,ITEM_NO,MEMBER_NO,CARTLIST_COUNT) values ('C00002','I00001','M00006',2);
Insert into ONECHO.CARTLIST (CARTLIST_NO,ITEM_NO,MEMBER_NO,CARTLIST_COUNT) values ('C00003','I00002','M00006',2);

REM INSERTING into ONECHO.WISHLIST
SET DEFINE OFF;
Insert into ONECHO.WISHLIST (WISHLIST_NO,ITEM_NO,MEMBER_NO,WISHLIST_MEMO) values ('W00001','I00001','M00007','Âò!!');
Insert into ONECHO.WISHLIST (WISHLIST_NO,ITEM_NO,MEMBER_NO,WISHLIST_MEMO) values ('W00002','I00002','M00006','Ä£±¸¼±¹°');

REM INSERTING into ONECHO.DELIVERY
SET DEFINE OFF;
Insert into ONECHO.DELIVERY (DELIVERY_CODE,DELIVERY_STATUS) values ('D1','¹è¼Û Àü');
Insert into ONECHO.DELIVERY (DELIVERY_CODE,DELIVERY_STATUS) values ('D2','¹è¼Û Áß');
Insert into ONECHO.DELIVERY (DELIVERY_CODE,DELIVERY_STATUS) values ('D3','¹è¼Û ¿Ï·á');

REM INSERTING into ONECHO.PAYMENT
SET DEFINE OFF;
Insert into ONECHO.PAYMENT (PAYMENT_CODE,PAYMENT_STATUS) values ('P1','ÀÔ±Ý Àü');
Insert into ONECHO.PAYMENT (PAYMENT_CODE,PAYMENT_STATUS) values ('P2','ÀÔ±Ý ÈÄ');

REM INSERTING into ONECHO.STATISTIC
SET DEFINE OFF;
Insert into ONECHO.STATISTIC (STATISTIC_NO,STATISTIC_VISITCOUNT,STATISTIC_TODAYJOIN,STATISTIC_CANCELCOUNT,STATISTIC_MEMBER,STATISTIC_DASK,STATISTIC_IASK,STATISTIC_CASK,STATISTIC_SALES,STATISTIC_DBEFORE,STATISTIC_NEWORDER,STATISTIC_CDATE) 
values ('STA00001',312312,84,10,300000,23,3,7,124123,70,100,to_date('20/06/01','RR/MM/DD'));
Insert into ONECHO.STATISTIC (STATISTIC_NO,STATISTIC_VISITCOUNT,STATISTIC_TODAYJOIN,STATISTIC_CANCELCOUNT,STATISTIC_MEMBER,STATISTIC_DASK,STATISTIC_IASK,STATISTIC_CASK,STATISTIC_SALES,STATISTIC_DBEFORE,STATISTIC_NEWORDER,STATISTIC_CDATE) 
values ('STA00002',100000,77,10,300077,12,8,7,523088,82,120,to_date('20/06/02','RR/MM/DD'));

REM INSERTING into ONECHO.ORDERLIST
SET DEFINE OFF;
Insert into ONECHO.ORDERLIST (ORDER_NO,ITEM_NO,MEMBER_NO,ORDER_DATE,ORDER_COUNT,ORDER_USEPOINT,ORDER_NAME,ORDER_PHONE1,ORDER_PHONE2,ORDER_PHONE3,ORDER_POSTCODE,ORDER_ADDRESS1,ORDER_ADDRESS2,ORDER_REQUEST,ORDER_DCOST,ORDER_CANCELREQUEST,ORDER_CANCELYN,DELIVERY_CODE,PAYMENT_CODE)
values ('O00001','I00001','M00006',to_date('20/06/02','RR/MM/DD'),3,0,'È«±æµ¿','010','1234','1234','98762','¼­¿ï½Ã ¼ÛÆÄ±¸ °¡¶ôµ¿ °¡¶ô¾ÆÆÄÆ®','110µ¿ 101È£',null,2500,'N','N','D1','P1');
Insert into ONECHO.ORDERLIST (ORDER_NO,ITEM_NO,MEMBER_NO,ORDER_DATE,ORDER_COUNT,ORDER_USEPOINT,ORDER_NAME,ORDER_PHONE1,ORDER_PHONE2,ORDER_PHONE3,ORDER_POSTCODE,ORDER_ADDRESS1,ORDER_ADDRESS2,ORDER_REQUEST,ORDER_DCOST,ORDER_CANCELREQUEST,ORDER_CANCELYN,DELIVERY_CODE,PAYMENT_CODE) 
values ('O00002','I00001','M00007',to_date('20/06/02','RR/MM/DD'),3,0,'È«±æµ¿','010','1234','1234','98762','¼­¿ï½Ã ¼ÛÆÄ±¸ °¡¶ôµ¿ °¡¶ô¾ÆÆÄÆ®','110µ¿ 101È£',null,2500,'N','N','D1','P1');
Insert into ONECHO.ORDERLIST (ORDER_NO,ITEM_NO,MEMBER_NO,ORDER_DATE,ORDER_COUNT,ORDER_USEPOINT,ORDER_NAME,ORDER_PHONE1,ORDER_PHONE2,ORDER_PHONE3,ORDER_POSTCODE,ORDER_ADDRESS1,ORDER_ADDRESS2,ORDER_REQUEST,ORDER_DCOST,ORDER_CANCELREQUEST,ORDER_CANCELYN,DELIVERY_CODE,PAYMENT_CODE) 
values ('O00003','I00001','M00006',to_date('20/06/02','RR/MM/DD'),1,0,'È«±æµ¿','010','1234','1234','98762','¼­¿ï½Ã ¼ÛÆÄ±¸ °¡¶ôµ¿ °¡¶ô¾ÆÆÄÆ®','110µ¿ 101È£',null,2500,'N','N','D1','P1');
Insert into ONECHO.ORDERLIST (ORDER_NO,ITEM_NO,MEMBER_NO,ORDER_DATE,ORDER_COUNT,ORDER_USEPOINT,ORDER_NAME,ORDER_PHONE1,ORDER_PHONE2,ORDER_PHONE3,ORDER_POSTCODE,ORDER_ADDRESS1,ORDER_ADDRESS2,ORDER_REQUEST,ORDER_DCOST,ORDER_CANCELREQUEST,ORDER_CANCELYN,DELIVERY_CODE,PAYMENT_CODE) 
values ('O00003','I00002','M00006',to_date('20/06/02','RR/MM/DD'),1,0,'È«±æµ¿','010','1234','1234','98762','¼­¿ï½Ã ¼ÛÆÄ±¸ °¡¶ôµ¿ °¡¶ô¾ÆÆÄÆ®','110µ¿ 101È£',null,2500,'N','N','D1','P1');

REM INSERTING into ONECHO.REVIEW
SET DEFINE OFF;
Insert into ONECHO.REVIEW (REVIEW_NO,ORDER_NO,ITEM_NO,MEMBER_NO,REVIEW_CDATE,REVIEW_RATE,REVIEW_CONTENT,REVIEW_UDATE,REVIEW_IMAGENAME,REVIEW_IMAGEPATH) 
values ('R00001','O00001','I00001','M00007',to_date('20/06/02','RR/MM/DD'),5,'ÁÁ¾Æ ¾ÆÁÖÁÁ¾Æ¿ä',to_date('20/06/02','RR/MM/DD'),'°í¹«³ª¹«.jpg','/IMAGES/ITEM/');
Insert into ONECHO.REVIEW (REVIEW_NO,ORDER_NO,ITEM_NO,MEMBER_NO,REVIEW_CDATE,REVIEW_RATE,REVIEW_CONTENT,REVIEW_UDATE,REVIEW_IMAGENAME,REVIEW_IMAGEPATH) 
values ('R00003','O00003','I00001','M00006',to_date('20/06/02','RR/MM/DD'),5,'°ø±â°¡ ´Þ¶ó¿ä ^^',to_date('20/06/02','RR/MM/DD'),'testsample.jpg','/IMAGES/ITEM/');

REM INSERTING into ONECHO.QNA
SET DEFINE OFF;
Insert into ONECHO.QNA (QNA_NO,MEMBER_NO,QNA_TITLE,QNA_CDATE,QNA_CONTENT,QNA_ANSWER,QNA_CATEGORY,QNA_PASSWORD,QNA_YN, QNA_IMAGENAME, QNA_IMAGEPATH) 
values ('Q00001','M00006','È­ºÐ»ö ¼±ÅÃ °¡´ÉÇÑ°¡¿ä?',to_date('20/06/02','RR/MM/DD'),'È­ºÐ»öÀÌ ±Ã±ÝÇØ¿ä',null,'»óÇ°','1234','N','testsample.jpg','/IMAGES/ITEM/');


--- VIEW ADD
-- Ä«Æ®¸®½ºÆ® ºä
CREATE OR REPLACE VIEW MEMBER_CARTLIST AS
SELECT CARTLIST_NO, CA.ITEM_NO, ITEM_NAME, ITEM_PRICE, ITEM_MAX, MEMBER_NO, CARTLIST_COUNT, II.IMAGE_NO, IMAGE_NAME
FROM CARTLIST CA
JOIN (
      select I.item_no, itemimage_no, IMAGE_NO, ITEM_NAME, ITEM_PRICE, ITEM_MAX
      from item I
      join (SELECT *
            FROM ITEMIMAGE
            WHERE itemimage_category=1) M on (I.item_no=M.item_no)
      ) II on (CA.item_no=II.item_no)
JOIN IMAGE IM ON (II.IMAGE_NO = IM.IMAGE_NO);

-- ¿À´õ È®ÀÎ
CREATE OR REPLACE VIEW ORDERCHK AS
SELECT ORDER_NO, IMAGE_PATH, ITEM_NO, ITEM_NAME, ITEM_MAX, DELIVERY_STATUS
FROM ORDERLIST O
JOIN ITEM IT ON(IT.ITEM_NO = O.ITEM_NO)
JOIN ITEMIMAGE II ON(II.ITEM_NO = IT.ITEM_NO)
JOIN IMAGE IM ON(IM.IMAGE_NO = II.IMAGE_NO)
JOIN DELIVERY D ON(D.DELIVERY_CODE = O.DELIVERY_CODE);
ROLLBACK;

-- À§½Ã È®ÀÎ
=======
-- ?Œì´ë¸??? œ
DROP TABLE ITEMIMAGE CASCADE CONSTRAINTS;
PROMPT DROPPING ITEMIMAGE...
DROP TABLE NOTICE CASCADE CONSTRAINTS;
PROMPT DROPPING NOTICE...
DROP TABLE QNA CASCADE CONSTRAINTS;
PROMPT DROPPING QNA...
DROP TABLE REVIEW CASCADE CONSTRAINTS;
PROMPT DROPPING REVIEW...
DROP TABLE STATISTIC CASCADE CONSTRAINTS;
PROMPT DROPPING STATISTIC...
DROP TABLE WISHLIST CASCADE CONSTRAINTS;
PROMPT DROPPING WISHLIST...
DROP TABLE CARTLIST CASCADE CONSTRAINTS;
PROMPT DROPPING CARTLIST...
DROP TABLE ORDERLIST CASCADE CONSTRAINTS;
PROMPT DROPPING ORDERLIST...
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
PROMPT DROPPING PAYMENT...
DROP TABLE IMAGE CASCADE CONSTRAINTS;
PROMPT DROPPING IMAGE...
DROP TABLE ITEM CASCADE CONSTRAINTS;
PROMPT DROPPING ITEM...
DROP TABLE KEYWORD CASCADE CONSTRAINTS;
PROMPT DROPPING KEYWORD...
DROP TABLE DELIVERY CASCADE CONSTRAINTS;
PROMPT DROPPING DELIVERY...
DROP TABLE MEMBER CASCADE CONSTRAINTS;
PROMPT DROPPING MEMBER...
DROP TABLE RANK CASCADE CONSTRAINTS;
PROMPT DROPPING RANK...

-- ?Œì´ë¸?ì¶”ê?
PROMPT CREATING RANK...
CREATE TABLE RANK
(
	RANK_NO	NVARCHAR2(30) CONSTRAINT PK_RANK PRIMARY KEY,
	RANK_NAME NVARCHAR2(60),
	RANK_POINTRAT NUMBER,
	RANK_POINTCAP NUMBER,
	RANK_POINTMIN NUMBER,
	RANK_POINTMAX NUMBER
);

COMMENT ON COLUMN RANK.RANK_NO IS '?±ê¸‰ë²ˆí˜¸(R00001~R00005)';
COMMENT ON COLUMN RANK.RANK_NAME IS '?±ê¸‰?´ë¦„(?¨ì•—,?ˆì‹¹,ê°?ì§?,?´ë§¤,?˜ë¬´)';
COMMENT ON COLUMN RANK.RANK_POINTRAT IS '?±ê¸‰?ë¦½??1%~5%)';
COMMENT ON COLUMN RANK.RANK_POINTCAP IS '?¬ì¸?¸ì‚¬?©í•œ??2000~10000)';
COMMENT ON COLUMN RANK.RANK_POINTMIN IS '?±ê¸‰??ìµœì†Œ êµ¬ë§¤ê¸ˆì•¡';
COMMENT ON COLUMN RANK.RANK_POINTMAX IS '?±ê¸‰??ìµœë? êµ¬ë§¤ ê¸ˆì•¡';

PROMPT CREATING MEMBER...
CREATE TABLE MEMBER
(
	MEMBER_NO NVARCHAR2(30) CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_ADMIN NVARCHAR2(2) DEFAULT 'N' NOT NULL CONSTRAINT CK_MEMBER_ADMIN CHECK(MEMBER_ADMIN IN('Y', 'N')),
	MEMBER_ID NVARCHAR2(30) NOT NULL CONSTRAINT UQ_MEMBER_ID UNIQUE,
	MEMBER_PWD NVARCHAR2(30),
	MEMBER_NAME	NVARCHAR2(30) NOT NULL,
	MEMBER_PHONE1 NVARCHAR2(10),
	MEMBER_PHONE2 NVARCHAR2(10),
	MEMBER_PHONE3 NVARCHAR2(10),
	MEMBER_EMAIL1 NVARCHAR2(30),
	MEMBER_EMAIL2 NVARCHAR2(30),
	MEMBER_POSTCODE	NVARCHAR2(30),
	MEMBER_ADDRESS1	NVARCHAR2(2000),
	MEMBER_ADDRESS2	NVARCHAR2(2000),
	MEMBER_JOINDATE	DATE DEFAULT SYSDATE NOT NULL,
	MEMBER_STATUS NVARCHAR2(2) DEFAULT 'N' NOT NULL CONSTRAINT CK_MEMBER_STATUS CHECK(MEMBER_STATUS IN('Y', 'N')),
	MEMBER_EXIT	NVARCHAR2(500),
	MEMBER_POINT NUMBER,
	MEMBER_RANK	NVARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '?Œì›ë²ˆí˜¸(M000001~)';
COMMENT ON COLUMN MEMBER.MEMBER_ADMIN IS 'ê´?ë¦¬ìž:Y, ?¼ë°˜?Œì›:N';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '?„ì´??? ë‹ˆ??;
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS 'ë¹„ë?ë²ˆí˜¸';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '?´ë¦„';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE1 IS '?°ë½ì²?';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE2 IS '?°ë½ì²?';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE3 IS '?°ë½ì²?';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL1 IS '?´ë©”??';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL2 IS '?´ë©”??';
COMMENT ON COLUMN MEMBER.MEMBER_POSTCODE IS '?°íŽ¸ë²ˆí˜¸';
COMMENT ON COLUMN MEMBER.MEMBER_ADDRESS1 IS 'ì£¼ì†Œ';
COMMENT ON COLUMN MEMBER.MEMBER_ADDRESS2 IS '?ì„¸ì£¼ì†Œ';
COMMENT ON COLUMN MEMBER.MEMBER_JOINDATE IS '?Œì›ê°??…ë‚ ì§?;
COMMENT ON COLUMN MEMBER.MEMBER_STATUS IS '?ˆí‡´:Y ê¸°ë³¸: N, ì¹´ì¹´??K ?Œì›?íƒœ';
COMMENT ON COLUMN MEMBER.MEMBER_EXIT IS '?ˆí‡´?¬ìœ ';
COMMENT ON COLUMN MEMBER.MEMBER_POINT IS '?¬ì¸??;
COMMENT ON COLUMN MEMBER.MEMBER_RANK IS '?±ê¸‰ë²ˆí˜¸(R1~R5)';

ALTER TABLE MEMBER ADD CONSTRAINT FK_RANK_TO_MEMBER FOREIGN KEY ( MEMBER_RANK )
REFERENCES RANK ( RANK_NO );


PROMPT CREATING DELIVERY...
CREATE TABLE DELIVERY
(
	DELIVERY_CODE NVARCHAR2(30) DEFAULT 'D1' CONSTRAINT PK_DELIVERY PRIMARY KEY,
	DELIVERY_STATUS	NVARCHAR2(100)
);

COMMENT ON COLUMN DELIVERY.DELIVERY_CODE IS 'D1 : ë°°ì†¡?? D2 : ë°°ì†¡ì¤? D3 : ë°°ì†¡?„ë£Œ(ë°°ì†¡ì½”ë“œ)';
COMMENT ON COLUMN DELIVERY.DELIVERY_STATUS IS 'ë°°ì†¡?? ë°°ì†¡ì¤? ë°°ì†¡?„ë£Œ(ë°°ì†¡?íƒœ)';

PROMPT CREATING KEYWORD...
CREATE TABLE KEYWORD (
	KEYWORD_NO NVARCHAR2(30) CONSTRAINT PK_KEYWORD PRIMARY KEY,
	KEYWORD_NAME NVARCHAR2(20)
);

COMMENT ON COLUMN KEYWORD.KEYWORD_NO IS '?¤ì›Œ?œë²ˆ??K1~)';
COMMENT ON COLUMN KEYWORD.KEYWORD_NAME IS 'ì¤‘ë³µ ? íƒ(?°ì†Œë¿œë¿œ, ë°˜ë ¤?™ë¬¼ ì¹œí™”)';


PROMPT CREATING ITEM...
CREATE TABLE ITEM 
(	
ITEM_NO NVARCHAR2(30) CONSTRAINT PK_ITEM PRIMARY KEY, 
ITEM_NAME NVARCHAR2(50) NOT NULL, 
ITEM_CATEGORY NVARCHAR2(2000) NOT NULL, 
KEYWORD_NO NVARCHAR2(30) NOT NULL, 
ITEM_PRICE NUMBER NOT NULL, 
ITEM_DISCOUNT NUMBER NOT NULL, 
ITEM_RATE NUMBER, 
ITEM_STOCK NUMBER NOT NULL, 
ITEM_DISPLAY NVARCHAR2(2) DEFAULT 'N' NOT NULL CONSTRAINT CK_ITEM_DISPLAY CHECK(ITEM_DISPLAY IN('Y', 'N')), 
ITEM_INFO NVARCHAR2(2000) NOT NULL, 
ITEM_CDATE DATE DEFAULT SYSDATE NOT NULL, 
ITEM_UDATE DATE DEFAULT SYSDATE NOT NULL, 
ITEM_SCOUNT NUMBER, 
ITEM_MAX NUMBER NOT NULL, 
ITEM_SALE NVARCHAR2(2) DEFAULT 'Y' CONSTRAINT CK_ITEM_SALE CHECK(ITEM_SALE IN('Y', 'N'))
);

COMMENT ON COLUMN ITEM.ITEM_NO IS '?í’ˆë²ˆí˜¸(I00001~)';
COMMENT ON COLUMN ITEM.ITEM_NAME IS '?í’ˆëª?;
COMMENT ON COLUMN ITEM.ITEM_CATEGORY IS '?í’ˆì¹´í…Œê³ ë¦¬';
COMMENT ON COLUMN ITEM.KEYWORD_NO IS '?¤ì›Œ?œë²ˆ??K1~)';
COMMENT ON COLUMN ITEM.ITEM_PRICE IS '?í’ˆê°?ê²?;
COMMENT ON COLUMN ITEM.ITEM_DISCOUNT IS '? ì¸ê°?;
COMMENT ON COLUMN ITEM.ITEM_RATE IS '?‰ì ';
COMMENT ON COLUMN ITEM.ITEM_STOCK IS '?í’ˆ?¬ê³ ';
COMMENT ON COLUMN ITEM.ITEM_DISPLAY IS '?„ì‹œ : Y, ë¹„ì „??: N';
COMMENT ON COLUMN ITEM.ITEM_INFO IS '?í’ˆ?¤ëª…?ìŠ¤??;
COMMENT ON COLUMN ITEM.ITEM_CDATE IS '?í’ˆ?±ë¡??;
COMMENT ON COLUMN ITEM.ITEM_UDATE IS 'ìµœì¢…?˜ì •??;
COMMENT ON COLUMN ITEM.ITEM_SCOUNT IS '?„ì ?ë§¤??;
COMMENT ON COLUMN ITEM.ITEM_MAX IS 'ìµœë?êµ¬ë§¤?˜ëŸ‰';
COMMENT ON COLUMN ITEM.ITEM_SALE IS '?ë§¤ì¤?: Y, ?ë§¤ì¤‘ì? : N';

ALTER TABLE item ADD CONSTRAINT FK_keyword_TO_item FOREIGN KEY ( keyword_no )
REFERENCES keyword ( keyword_no );


PROMPT CREATING IMAGE...
CREATE TABLE IMAGE 
(
	IMAGE_NO NVARCHAR2(30) CONSTRAINT PK_IMAGE PRIMARY KEY,
	IMAGE_PATH NVARCHAR2(2000),
	IMAGE_NAME NVARCHAR2(2000)
);

COMMENT ON COLUMN IMAGE.IMAGE_NO IS '?´ë?ì§?ë²ˆí˜¸(IMG00001~)';
COMMENT ON COLUMN IMAGE.IMAGE_PATH IS '?´ë?ì§? ê²½ë¡œ';
COMMENT ON COLUMN IMAGE.IMAGE_NAME IS '?´ë?ì§? ëª…ì¹­';


PROMPT CREATING PAYMENT...
CREATE TABLE PAYMENT 
(
	PAYMENT_CODE NVARCHAR2(30) DEFAULT 'P1' CONSTRAINT PK_PAYMENT PRIMARY KEY,
	PAYMENT_STATUS NVARCHAR2(100)
);

COMMENT ON COLUMN PAYMENT.PAYMENT_CODE IS 'P1 : ?…ê¸ˆ ?? P2 : ?…ê¸ˆ ???…ê¸ˆì½”ë“œ)';
COMMENT ON COLUMN PAYMENT.PAYMENT_STATUS IS '?…ê¸ˆ ?? ?…ê¸ˆ ???…ê¸ˆ?íƒœ)';


PROMPT CREATING ORDERLIST...
CREATE TABLE ORDERLIST 
(
	ORDER_NO NVARCHAR2(30),
	ITEM_NO	NVARCHAR2(30),
	MEMBER_NO NVARCHAR2(30) NOT NULL,
	ORDER_DATE DATE DEFAULT SYSDATE NOT NULL,
	ORDER_COUNT	NUMBER NOT NULL,
	ORDER_USEPOINT	NUMBER NOT NULL,
	ORDER_NAME	NVARCHAR2(100) NOT NULL,
	ORDER_PHONE1 NVARCHAR2(10) NOT NULL,
	ORDER_PHONE2 NVARCHAR2(10) NOT NULL,
	ORDER_PHONE3 NVARCHAR2(10) NOT NULL,
	ORDER_POSTCODE NVARCHAR2(30) NOT NULL,
	ORDER_ADDRESS1 NVARCHAR2(2000) NOT NULL,
	ORDER_ADDRESS2 NVARCHAR2(2000) NOT NULL,
	ORDER_REQUEST NVARCHAR2(2000),
	ORDER_DCOST	NUMBER NOT NULL,
	ORDER_CANCELREQUEST	NVARCHAR2(2) DEFAULT 'N' CONSTRAINT CK_ORDER_CANCELREQUEST CHECK(ORDER_CANCELREQUEST IN('Y', 'N')),
	ORDER_CANCELYN NVARCHAR2(2) DEFAULT 'N' CONSTRAINT CK_ORDER_CANCELYN CHECK(ORDER_CANCELYN IN('Y', 'N')),
	DELIVERY_CODE NVARCHAR2(10) NOT NULL,
	PAYMENT_CODE NVARCHAR2(10) DEFAULT 'P1' NOT NULL
);

ALTER TABLE ORDERLIST ADD CONSTRAINT PK_ORDERLIST PRIMARY KEY (
	ORDER_NO,
	ITEM_NO
);

ALTER TABLE ORDERLIST ADD CONSTRAINT FK_ITEM_TO_ORDERLIST FOREIGN KEY ( ITEM_NO )
REFERENCES ITEM ( ITEM_NO );
ALTER TABLE ORDERLIST ADD CONSTRAINT FK_MEMBER_TO_ORDERLIST FOREIGN KEY ( MEMBER_NO )
REFERENCES MEMBER (	MEMBER_NO );
ALTER TABLE ORDERLIST ADD CONSTRAINT FK_DELIVERY_TO_ORDERLIST FOREIGN KEY ( DELIVERY_CODE )
REFERENCES DELIVERY ( DELIVERY_CODE );
ALTER TABLE ORDERLIST ADD CONSTRAINT FK_PAYMENT_TO_ORDERLIST FOREIGN KEY ( PAYMENT_CODE )
REFERENCES PAYMENT ( PAYMENT_CODE );


COMMENT ON COLUMN ORDERLIST.ORDER_NO IS 'ì£¼ë¬¸ë²ˆí˜¸(O00001~ )';
COMMENT ON COLUMN ORDERLIST.ITEM_NO IS '?í’ˆë²ˆí˜¸(I1~)';
COMMENT ON COLUMN ORDERLIST.MEMBER_NO IS '?Œì›ë²ˆí˜¸(M1~)';
COMMENT ON COLUMN ORDERLIST.ORDER_DATE IS 'ì£¼ë¬¸?¼ì‹œ';
COMMENT ON COLUMN ORDERLIST.ORDER_COUNT IS 'ì£¼ë¬¸?˜ëŸ‰';
COMMENT ON COLUMN ORDERLIST.ORDER_USEPOINT IS '?¬ìš©?¬ì¸??;
COMMENT ON COLUMN ORDERLIST.ORDER_NAME IS '?˜ë ¹?ì´ë¦?;
COMMENT ON COLUMN ORDERLIST.ORDER_PHONE1 IS '?˜ë ¹?ì „?”ë²ˆ??';
COMMENT ON COLUMN ORDERLIST.ORDER_PHONE2 IS '?˜ë ¹?ì „?”ë²ˆ??';
COMMENT ON COLUMN ORDERLIST.ORDER_PHONE3 IS '?˜ë ¹?ì „?”ë²ˆ??';
COMMENT ON COLUMN ORDERLIST.ORDER_POSTCODE IS '?˜ë ¹?ìš°?¸ë²ˆ??;
COMMENT ON COLUMN ORDERLIST.ORDER_ADDRESS1 IS '?˜ë ¹?ì£¼??;
COMMENT ON COLUMN ORDERLIST.ORDER_ADDRESS2 IS '?˜ë ¹?ìƒ?¸ì£¼??;
COMMENT ON COLUMN ORDERLIST.ORDER_REQUEST IS 'ë°°ì†¡?œìš”ì²?‚¬??;
COMMENT ON COLUMN ORDERLIST.ORDER_DCOST IS 'ë°°ì†¡ë¹?;
COMMENT ON COLUMN ORDERLIST.ORDER_CANCELREQUEST IS 'ê¸°ë³¸: N , ì·¨ì†Œ : Y';
COMMENT ON COLUMN ORDERLIST.ORDER_CANCELYN IS 'ê¸°ë³¸: N , ?¹ì¸ : Y (ì£¼ë¬¸ ?? œ ?¨ê³¼)';
COMMENT ON COLUMN ORDERLIST.DELIVERY_CODE IS 'D1 : ë°°ì†¡?? D2 : ë°°ì†¡ì¤? D3 : ë°°ì†¡?„ë£Œ';
COMMENT ON COLUMN ORDERLIST.PAYMENT_CODE IS 'P1 : ?…ê¸ˆ ?? P2 : ?…ê¸ˆ ??;


PROMPT CREATING CARTLIST...
CREATE TABLE CARTLIST 
(
	CARTLIST_NO	NVARCHAR2(30) CONSTRAINT PK_CARTLIST PRIMARY KEY,
	ITEM_NO NVARCHAR2(30) NOT NULL,
	MEMBER_NO NVARCHAR2(30) NOT NULL,
	CARTLIST_COUNT NUMBER
);

ALTER TABLE CARTLIST ADD CONSTRAINT FK_ITEM_TO_CARTLIST FOREIGN KEY ( ITEM_NO )
REFERENCES ITEM ( ITEM_NO );

ALTER TABLE CARTLIST ADD CONSTRAINT FK_MEMBER_TO_CARTLIST FOREIGN KEY ( MEMBER_NO )
REFERENCES MEMBER ( MEMBER_NO );

COMMENT ON COLUMN CARTLIST.CARTLIST_NO IS '?¥ë°”êµ¬ë‹ˆë²ˆí˜¸(C00001~)';
COMMENT ON COLUMN CARTLIST.ITEM_NO IS '?í’ˆë²ˆí˜¸';
COMMENT ON COLUMN CARTLIST.MEMBER_NO IS '?Œì›ë²ˆí˜¸(M1~)';
COMMENT ON COLUMN CARTLIST.CARTLIST_COUNT IS '?˜ëŸ‰';


PROMPT CREATING CARTLIST...
CREATE TABLE WISHLIST 
(
	WISHLIST_NO	NVARCHAR2(30) CONSTRAINT PK_WISHLIST PRIMARY KEY,
	ITEM_NO	NVARCHAR2(30) NOT NULL,
	MEMBER_NO NVARCHAR2(30) NOT NULL,
	WISHLIST_MEMO NVARCHAR2(500)
);

ALTER TABLE WISHLIST ADD CONSTRAINT FK_ITEM_TO_WISHLIST FOREIGN KEY ( ITEM_NO )
REFERENCES ITEM ( ITEM_NO );
ALTER TABLE WISHLIST ADD CONSTRAINT FK_MEMBER_TO_WISHLIST FOREIGN KEY ( MEMBER_NO )
REFERENCES MEMBER ( MEMBER_NO );

COMMENT ON COLUMN WISHLIST.WISHLIST_NO IS '?„ì‹œë¦¬ìŠ¤?¸ë²ˆ??W00001~)';
COMMENT ON COLUMN WISHLIST.ITEM_NO IS '?í’ˆë²ˆí˜¸';
COMMENT ON COLUMN WISHLIST.MEMBER_NO IS '?Œì›ë²ˆí˜¸(M1~)';
COMMENT ON COLUMN WISHLIST.WISHLIST_MEMO IS 'ë©”ëª¨';


PROMPT CREATING STATISTIC...
CREATE TABLE STATISTIC 
(
	STATISTIC_NO NVARCHAR2(30) CONSTRAINT PK_STATISTIC PRIMARY KEY,
	STATISTIC_VISITCOUNT NUMBER,
	STATISTIC_TODAYJOIN NUMBER,
	STATISTIC_CANCELCOUNT NUMBER,
	STATISTIC_MEMBER NUMBER,
	STATISTIC_DASK NUMBER,
	STATISTIC_IASK NUMBER,
	STATISTIC_CASK NUMBER,
	STATISTIC_SALES NUMBER,
	STATISTIC_DBEFORE NUMBER,
	STATISTIC_NEWORDER NUMBER,
	STATISTIC_CDATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN STATISTIC.STATISTIC_NO IS '?¼ì¼?µê³„(sta00001-)';
COMMENT ON COLUMN STATISTIC.STATISTIC_VISITCOUNT IS 'ë°©ë¬¸?ìˆ˜';
COMMENT ON COLUMN STATISTIC.STATISTIC_TODAYJOIN IS 'ê¸ˆì¼ê°???;
COMMENT ON COLUMN STATISTIC.STATISTIC_CANCELCOUNT IS 'ì·¨ì†Œ?”ì²­';
COMMENT ON COLUMN STATISTIC.STATISTIC_MEMBER IS '?„ì²´?Œì›';
COMMENT ON COLUMN STATISTIC.STATISTIC_DASK IS 'ë°°ì†¡ë¬¸ì˜';
COMMENT ON COLUMN STATISTIC.STATISTIC_IASK IS '?í’ˆë¬¸ì˜';
COMMENT ON COLUMN STATISTIC.STATISTIC_CASK IS 'ì·¨ì†Œë¬¸ì˜';
COMMENT ON COLUMN STATISTIC.STATISTIC_SALES IS 'ê¸ˆì¼ë§¤ì¶œ';
COMMENT ON COLUMN STATISTIC.STATISTIC_DBEFORE IS 'ë°°ì†¡??ê¸?;
COMMENT ON COLUMN STATISTIC.STATISTIC_NEWORDER IS '? ê·œì£¼ë¬¸';
COMMENT ON COLUMN STATISTIC.STATISTIC_CDATE IS '?±ë¡??;


PROMPT CREATING REVIEW...
CREATE TABLE REVIEW 
(
	REVIEW_NO NVARCHAR2(30) CONSTRAINT PK_REVIEW PRIMARY KEY,
	ORDER_NO NVARCHAR2(30) NOT NULL,
	ITEM_NO	NVARCHAR2(30) NOT NULL,
	MEMBER_NO NVARCHAR2(30) NOT NULL,
	REVIEW_CDATE DATE DEFAULT SYSDATE,
	REVIEW_RATE	NUMBER,
	REVIEW_CONTENT NVARCHAR2(2000),
	REVIEW_UDATE DATE DEFAULT SYSDATE,
	REVIEW_IMAGENAME NVARCHAR2(2000),
    REVIEW_IMAGEPATH NVARCHAR2(2000)
);

ALTER TABLE REVIEW ADD CONSTRAINT FK_ORDERLIST_TO_REVIEW FOREIGN KEY ( ORDER_NO, ITEM_NO )
REFERENCES ORDERLIST ( ORDER_NO, ITEM_NO );
ALTER TABLE REVIEW ADD CONSTRAINT FK_MEMBER_TO_REVIEW FOREIGN KEY ( MEMBER_NO )
REFERENCES MEMBER ( MEMBER_NO );

COMMENT ON COLUMN REVIEW.REVIEW_NO IS 'ë¦¬ë·°ë²ˆí˜¸(R00001~ )';
COMMENT ON COLUMN REVIEW.ORDER_NO IS 'ì£¼ë¬¸ë²ˆí˜¸(O00001~ )';
COMMENT ON COLUMN REVIEW.ITEM_NO IS '?í’ˆë²ˆí˜¸(I00001~ )';
COMMENT ON COLUMN REVIEW.MEMBER_NO IS '?Œì›ë²ˆí˜¸';
COMMENT ON COLUMN REVIEW.REVIEW_CDATE IS 'ë¦¬ë·°?±ë¡??;
COMMENT ON COLUMN REVIEW.REVIEW_RATE IS '?‰ì ';
COMMENT ON COLUMN REVIEW.REVIEW_CONTENT IS 'ë¦¬ë·°?´ìš©';
COMMENT ON COLUMN REVIEW.REVIEW_UDATE IS 'ë¦¬ë·°?˜ì •??;
COMMENT ON COLUMN REVIEW.REVIEW_IMAGENAME IS '?´ë?ì§??´ë¦„';
COMMENT ON COLUMN REVIEW.REVIEW_IMAGEPATH IS '?´ë?ì§?ê²½ë¡œ';


PROMPT CREATING QNA...
CREATE TABLE QNA 
(
	QNA_NO NVARCHAR2(30) CONSTRAINT PK_QNA PRIMARY KEY,
	MEMBER_NO NVARCHAR2(30) NOT NULL,
	QNA_TITLE NVARCHAR2(100) NOT NULL,
	QNA_CDATE DATE,
	QNA_CONTENT	NVARCHAR2(2000),
	QNA_ANSWER NVARCHAR2(2000),
	QNA_CATEGORY NVARCHAR2(20) NOT NULL,
    QNA_PASSWORD NVARCHAR2(20) NOT NULL,
	QNA_YN NVARCHAR2(2) DEFAULT 'N' CONSTRAINT CK_QNA_YN CHECK(QNA_YN IN('Y', 'N')),
	QNA_IMAGENAME NVARCHAR2(2000),
    QNA_IMAGEPATH NVARCHAR2(2000)
);

ALTER TABLE QNA ADD CONSTRAINT FK_MEMBER_TO_QNA FOREIGN KEY ( MEMBER_NO )
REFERENCES MEMBER ( MEMBER_NO );

COMMENT ON COLUMN QNA.QNA_NO IS 'ê¸?ë²ˆí˜¸(Q00001~)';
COMMENT ON COLUMN QNA.MEMBER_NO IS '?Œì›ë²ˆí˜¸(M1~)';
COMMENT ON COLUMN QNA.QNA_TITLE IS 'ì§ˆë¬¸?œëª©';
COMMENT ON COLUMN QNA.QNA_CDATE IS 'ê²Œì‹œ??;
COMMENT ON COLUMN QNA.QNA_CONTENT IS '?´ìš©';
COMMENT ON COLUMN QNA.QNA_ANSWER IS '?µë?';
COMMENT ON COLUMN QNA.QNA_CATEGORY IS 'ë¶„ë¥˜';
COMMENT ON COLUMN QNA.QNA_PASSWORD IS 'ë¹„ë?ë²ˆí˜¸';
COMMENT ON COLUMN QNA.QNA_YN IS '?µë? ??: N, ?µë? : Y';
COMMENT ON COLUMN QNA.QNA_IMAGENAME IS '?´ë?ì§??´ë¦„';
COMMENT ON COLUMN QNA.QNA_IMAGEPATH IS '?´ë?ì§?ê²½ë¡œ';


PROMPT CREATING NOTICE...
CREATE TABLE NOTICE (
	NOTICE_NO NVARCHAR2(30) CONSTRAINT PK_NOTICE PRIMARY KEY,
	MEMBER_NO NVARCHAR2(30) NOT NULL,
	NOTICE_TITLE NVARCHAR2(100) NOT NULL,
	NOTICE_CDATE DATE,
	NOTICE_CONTENT NVARCHAR2(2000),
    NOTICE_IMAGENAME NVARCHAR2(2000),
    NOTICE_IMAGEPATH NVARCHAR2(2000)
);

ALTER TABLE NOTICE ADD CONSTRAINT FK_MEMBER_TO_NOTICE FOREIGN KEY ( MEMBER_NO )
REFERENCES MEMBER ( MEMBER_NO );

COMMENT ON COLUMN NOTICE.NOTICE_NO IS 'ê³µì?ê¸?ë²ˆí˜¸(N00001~)';
COMMENT ON COLUMN NOTICE.MEMBER_NO IS '?Œì›ë²ˆí˜¸(M00001~)';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '?œëª©';
COMMENT ON COLUMN NOTICE.NOTICE_CDATE IS 'ê²Œì‹œ??;
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '?´ìš©';
COMMENT ON COLUMN NOTICE.NOTICE_IMAGENAME IS '?´ë?ì§??´ë¦„';
COMMENT ON COLUMN NOTICE.NOTICE_IMAGEPATH IS '?´ë?ì§?ê²½ë¡œ';


PROMPT CREATING ITEMIMAGE...
CREATE TABLE ITEMIMAGE (
    ITEMIMAGE_NO NVARCHAR2(30) CONSTRAINT PK_ITEMIMAGE PRIMARY KEY,
    ITEM_NO   NVARCHAR2(30),
    IMAGE_NO NVARCHAR2(30),
    ITEMIMAGE_CATEGORY NUMBER
);

ALTER TABLE ITEMIMAGE ADD CONSTRAINT FK_ITEM_TO_ITEMIMAGE FOREIGN KEY ( ITEM_NO )
REFERENCES ITEM ( ITEM_NO );
ALTER TABLE ITEMIMAGE ADD CONSTRAINT FK_IMAGE_TO_ITEMIMAGE FOREIGN KEY ( IMAGE_NO )
REFERENCES IMAGE ( IMAGE_NO );

COMMENT ON COLUMN ITEMIMAGE.ITEMIMAGE_NO IS '?í’ˆ?´ë?ì§?ë²ˆí˜¸(Ii00001~)';
COMMENT ON COLUMN ITEMIMAGE.ITEM_NO IS '?í’ˆë²ˆí˜¸(I00001~)';
COMMENT ON COLUMN ITEMIMAGE.IMAGE_NO IS '?´ë?ì§?ë²ˆí˜¸(img00001~)';
COMMENT ON COLUMN ITEMIMAGE.ITEMIMAGE_CATEGORY IS 'ë©”ì¸?´ë?ì§?:1,?œë¸Œ?´ë?ì§?:2';

--------------------------------------------------------
-- DDL for Sequence IMAGE_SEQ
DROP SEQUENCE IMAGE_SEQ;
DROP SEQUENCE ITEMIMAGE_SEQ;
DROP SEQUENCE ITEM_SEQ;

CREATE SEQUENCE  IMAGE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 
START WITH 24 
CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE ITEMIMAGE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 
START WITH 25 
CACHE 20 NOORDER  NOCYCLE ;

CREATE SEQUENCE ITEM_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 
START WITH 23 
CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------

-- ?°ì´??ì¶”ê?
REM INSERTING into ONECHO.RANK
SET DEFINE OFF;
Insert into ONECHO.RANK (RANK_NO,RANK_NAME,RANK_POINTRAT,RANK_POINTCAP,RANK_POINTMIN,RANK_POINTMAX) values ('R1','?¨ì•—',1,2000,0,50000);
Insert into ONECHO.RANK (RANK_NO,RANK_NAME,RANK_POINTRAT,RANK_POINTCAP,RANK_POINTMIN,RANK_POINTMAX) values ('R2','?ˆì‹¹',2,4000,50001,200000);
Insert into ONECHO.RANK (RANK_NO,RANK_NAME,RANK_POINTRAT,RANK_POINTCAP,RANK_POINTMIN,RANK_POINTMAX) values ('R3','ê°?ì§?',3,6000,200001,500000);
Insert into ONECHO.RANK (RANK_NO,RANK_NAME,RANK_POINTRAT,RANK_POINTCAP,RANK_POINTMIN,RANK_POINTMAX) values ('R4','?´ë§¤',4,8000,500001,1000000);
Insert into ONECHO.RANK (RANK_NO,RANK_NAME,RANK_POINTRAT,RANK_POINTCAP,RANK_POINTMIN,RANK_POINTMAX) values ('R5','?˜ë¬´',5,10000,1000001,999999999);

REM INSERTING into ONECHO.MEMBER
SET DEFINE OFF;
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK) 
values ('M00001','Y','admin1','admin1','?•ìœ ì§?,'010','1234','5678','admin1','@oncho.com','12345','2','2',to_date('20/06/02','RR/MM/DD'),'N',null,2000,'R2');
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK) 
values ('M00002','Y','admin2','admin2','ê°•ê´‘??,'010','1234','5678','admin2','@oncho.com','12345','2','2',to_date('20/06/02','RR/MM/DD'),'N',null,4000,'R2');
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK) 
values ('M00003','Y','admin3','admin3','?´ì•„??,'010','1234','5678','admin3','@oncho.com','12345','3','3',to_date('20/06/02','RR/MM/DD'),'N',null,8000,'R3');
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK)
values ('M00004','Y','admin4','admin4','ê¹?ê²½ë‚¨','010','1234','5678','admin4','@oncho.com','12345','4','4',to_date('20/06/02','RR/MM/DD'),'N',null,12000,'R4');
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK)
values ('M00005','Y','admin5','admin5','?´ìˆ˜??,'010','1234','5678','admin5','@oncho.com','12345','5','5',to_date('20/06/02','RR/MM/DD'),'N',null,16000,'R5');
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK)
values ('M00006','N','user1','user1','?ê¸¸??,'010','2828','8282','user1','@naver.com','06234','?œìš¸?¹ë³„??ê°•ë‚¨êµ??Œí—¤??ë¡?4ê¸?6 (??‚¼??','2ì¸?,to_date('20/06/02','RR/MM/DD'),'N',null,2000,'R1');
Insert into ONECHO.MEMBER (MEMBER_NO,MEMBER_ADMIN,MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_PHONE1,MEMBER_PHONE2,MEMBER_PHONE3,MEMBER_EMAIL1,MEMBER_EMAIL2,MEMBER_POSTCODE,MEMBER_ADDRESS1,MEMBER_ADDRESS2,MEMBER_JOINDATE,MEMBER_STATUS,MEMBER_EXIT,MEMBER_POINT,MEMBER_RANK)
values ('M00007','N','user2','user2','?ê¸¸??,'010','7568','5678','user2','@gmail.com','06234','?œìš¸?¹ë³„??ê°•ë‚¨êµ??Œí—¤??ë¡?4ê¸?6 (??‚¼??','3ì¸?,to_date('20/06/03','RR/MM/DD'),'N',null,9000,'R2');

REM INSERTING into ONECHO.KEYWORD
SET DEFINE OFF;
Insert into ONECHO.KEYWORD (KEYWORD_NO,KEYWORD_NAME) values ('K1','?°ì†Œë¿œë¿œ');
Insert into ONECHO.KEYWORD (KEYWORD_NO,KEYWORD_NAME) values ('K2','ë°˜ë ¤?™ë¬¼ ì¹œí™”');
Insert into ONECHO.KEYWORD (KEYWORD_NO,KEYWORD_NAME) values ('K3','?°ì†Œë¿œë¿œ ë°˜ë ¤?™ë¬¼ ì¹œí™”');

REM INSERTING into ONECHO.IMAGE
SET DEFINE OFF;
Insert into ONECHO.IMAGE (IMAGE_NO,IMAGE_PATH,IMAGE_NAME) values ('IMG00001','/IMAGES/ITEM/','ê³ ë¬´?˜ë¬´.jpg');
Insert into ONECHO.IMAGE (IMAGE_NO,IMAGE_PATH,IMAGE_NAME) values ('IMG00002','/IMAGES/ITEM/','smim.jpg');
Insert into ONECHO.IMAGE (IMAGE_NO,IMAGE_PATH,IMAGE_NAME) values ('IMG00003','/IMAGES/ITEM/','testsample.jpg');
Insert into ONECHO.IMAGE (IMAGE_NO,IMAGE_PATH,IMAGE_NAME) values ('IMG00004','/IMAGES/ITEM/','testsample.jpg');

REM INSERTING into ONECHO.ITEM
SET DEFINE OFF;
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00001','?¼ìž?˜ì—¼?¸ë??œì‹œ??,'HANGING','K3',26500,25000,0,28,'Y','ì§‘ì— ?±ê·¸?¬ì????”í•´ì¤?ë¿??„ë‹ˆ??ê³µê¸°?•í™” ?¥ë ¥???°ì–´???¼ìž?˜ì—¼?¸ë??œì‹œ??,to_date('20/05/21','RR/MM/DD'),to_date('20/05/21','RR/MM/DD'),13,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00002','ë¬¸ìƒ¤??,'SOIL','K1',25000,24000,0,34,'Y','?´ë¦„ ê·¸ë?ë¡??¬ë¹›??ë¨¸ê¸ˆ????•œ ?¤ë¬˜???‰ì´ ë§¤ë ¥?ì¸ ë¬¸ìƒ¤??,to_date('20/05/22','RR/MM/DD'),to_date('20/05/22','RR/MM/DD'),8,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00003','ëª¬ìŠ¤?Œë¼','SOIL','K1',27000,26000,0,21,'Y','?“ì? ?Žì´ ì£¼ëŠ” ?´êµ­?ì¸ ë¶„ìœ„ê¸°ë? ?´ëŠ” ëª¬ìŠ¤?Œë¼',to_date('20/05/23','RR/MM/DD'),to_date('20/05/23','RR/MM/DD'),1,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00004','?”ì‹œ?”ì•„','HANGING','K3',19500,17000,0,15,'Y','?™ê??™ê????…ì‚¬ê·????°ìƒ‰ ?Œë‘ë¦¬ê? ë§¤ë ¥?ì¸ ?”ì‹œ?”ì•„',to_date('20/05/24','RR/MM/DD'),to_date('20/05/24','RR/MM/DD'),1,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00005','?¼íƒ„?¬ë ˆ?¤íŠ¸','SOIL','K1',28900,26900,0,19,'Y','?¤íŒŒ?°í•„ë¦„ê³¼ ?¤ë…¸?°ì‚¬?Œì´?´ê? ?¼íƒ„ë°”êµ¬?ˆì— ?´ê²¨ ?´êµ­?ì¸ ë¶„ìœ„ê¸°ë? ??',to_date('20/05/25','RR/MM/DD'),to_date('20/05/25','RR/MM/DD'),2,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00006','?¤íŒŒ?°í•„ë¦?,'WATER','K1',22000,21000,0,31,'Y','?¬ê³„???´ë‚´ ?„ë¦„?¤ìš´ ê½ƒê³¼ ?¨ê»˜?˜ëŠ” ì¦ê±°?? ?¤íŒŒ?°í•„ë¦?,to_date('20/05/26','RR/MM/DD'),to_date('20/05/26','RR/MM/DD'),3,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00007','?‰ìš´ëª?,'WATER','K1',20000,17000,0,28,'Y','?´ì‚°?”íƒ„?? ?¬ë¦„?Œë°?ˆë“œ, ë²¤ì   ?±ì˜ ? í•´ë¬¼ì§ˆ??ëª¨ë‘ ?¡ìˆ˜?´ì£¼???‰ìš´ëª?,to_date('20/05/27','RR/MM/DD'),to_date('20/05/27','RR/MM/DD'),1,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00008','?°ì„¸ë² ë¦¬??,'SOIL','K1',23500,22500,0,21,'Y','?¬ë§‰???ˆëŠ” ? ì¸?? ?ëª…???•ì´??ë¶ˆë¦¬???°ì„¸ë² ë¦¬??,to_date('20/05/28','RR/MM/DD'),to_date('20/05/28','RR/MM/DD'),1,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00009','?¸ë??Œë¼ë¦¬ì?','SOIL','K3',24500,23000,0,55,'Y','ì§?êµ¬ìƒ?ì„œ ê°???ê°•ë ¥??ê³µê¸°ì²? •ê¸??¸ë??œì‹œ??,to_date('20/05/29','RR/MM/DD'),to_date('20/05/29','RR/MM/DD'),2,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00010','?¤í‚¨?µì„œ??,'WATER','K1',15000,14000,0,43,'Y','?˜ê²½?ì‘?¥ì´ ?°ì–´??ë°˜ë ¤?ë¬¼ ì´ˆë³´?ë„ ì¹œêµ¬ê°? ?????ˆëŠ” ?¤í‚¨?µì„œ??,to_date('20/05/30','RR/MM/DD'),to_date('20/05/30','RR/MM/DD'),3,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00011','?˜ê²½ëª¬ìŠ¤?Œë¼','WATER','K1',27000,24000,0,5,'Y','?•í™”?¥ë ¥???°ì–´????ì§‘ì´???¬ë¬´?¤ì—??ê°ê´‘ë°›ëŠ” ?˜ê²½ëª¬ìŠ¤?Œë¼',to_date('20/05/31','RR/MM/DD'),to_date('20/05/31','RR/MM/DD'),5,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00012','?Œì´ë¸”ì•¼??,'WATER','K3',22500,19500,0,7,'Y','ê³µê¸°?•í™”??ë¬¼ë¡  ê°??µíš¨ê³¼ê¹Œì§? ?ì›”???Œì´ë¸”ì•¼??,to_date('20/06/01','RR/MM/DD'),to_date('20/06/01','RR/MM/DD'),2,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00013','?¤ë…¸?°ì‚¬?Œì´??,'WATER','K1',28000,27000,0,9,'Y','ë¶??? ?‰ìš´??ê°??¸ë‹¤ì¤??¤ëŠ” ?¤ë…¸?°ì‚¬?Œì´??,to_date('20/06/02','RR/MM/DD'),to_date('20/06/02','RR/MM/DD'),7,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00014','?´ì˜¤?œì‚¬','HANGING','K3',20000,16500,0,30,'Y','?¬ê¸°???‘ì?ë§?ê³µê¸°ë¥??•í™”?œì¼œì£¼ëŠ” ?´ì˜¤?œì‚¬',to_date('20/06/03','RR/MM/DD'),to_date('20/06/03','RR/MM/DD'),3,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00015','?„ë ˆ?„íŽ˜??,'WATER','K3',30000,26000,0,9,'Y','ê·??¬ìš´ ë¹„ì£¼?¼ì— ê±¸ë§ž??ê·??¬ìš´ ?´ë¦„, ?„ë ˆ?„íŽ˜??,to_date('20/06/04','RR/MM/DD'),to_date('20/06/04','RR/MM/DD'),5,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00016','?¤íˆ¬??,'SOIL','K1',21500,19500,0,11,'Y','ë¯¸êµ­ NASA?ì„œ???¸ì¦??ê³µê¸°?•í™” ?¥ë ¥??ê°?ì§??¤íˆ¬??,to_date('20/06/05','RR/MM/DD'),to_date('20/06/05','RR/MM/DD'),20,10,'Y');
Insert into ONECHO.ITEM (ITEM_NO,ITEM_NAME,ITEM_CATEGORY,KEYWORD_NO,ITEM_PRICE,ITEM_DISCOUNT,ITEM_RATE,ITEM_STOCK,ITEM_DISPLAY,ITEM_INFO,ITEM_CDATE,ITEM_UDATE,ITEM_SCOUNT,ITEM_MAX,ITEM_SALE) 
values ('I00017','ë§ˆë¦¬ëª?,'WATER','K2',25000,22500,0,20,'Y','ê¸°ë¶„??ì¢‹ì„??ë¬??„ë? ?¥ë‘¥, ë³´ê¸°ë§??´ë„ ?‰ë³µ?´ì???ê·??¬ìš´ ë§ˆë¦¬ëª?,to_date('20/06/06','RR/MM/DD'),to_date('20/06/06','RR/MM/DD'),19,10,'Y');


REM INSERTING into ONECHO.ITEMIMAGE
SET DEFINE OFF;
Insert into ONECHO.ITEMIMAGE (ITEMIMAGE_NO,ITEM_NO,IMAGE_NO,ITEMIMAGE_CATEGORY) values ('II00001','I00001','IMG00001',1);
Insert into ONECHO.ITEMIMAGE (ITEMIMAGE_NO,ITEM_NO,IMAGE_NO,ITEMIMAGE_CATEGORY) values ('II00002','I00001','IMG00002',2);
Insert into ONECHO.ITEMIMAGE (ITEMIMAGE_NO,ITEM_NO,IMAGE_NO,ITEMIMAGE_CATEGORY) values ('II00003','I00002','IMG00003',1);
Insert into ONECHO.ITEMIMAGE (ITEMIMAGE_NO,ITEM_NO,IMAGE_NO,ITEMIMAGE_CATEGORY) values ('II00004','I00002','IMG00002',2);
Insert into ONECHO.ITEMIMAGE (ITEMIMAGE_NO,ITEM_NO,IMAGE_NO,ITEMIMAGE_CATEGORY) values ('II00005','I00003','IMG00004',1);
Insert into ONECHO.ITEMIMAGE (ITEMIMAGE_NO,ITEM_NO,IMAGE_NO,ITEMIMAGE_CATEGORY) values ('II00006','I00003','IMG00005',2);

REM INSERTING into ONECHO.CARTLIST
SET DEFINE OFF;
Insert into ONECHO.CARTLIST (CARTLIST_NO,ITEM_NO,MEMBER_NO,CARTLIST_COUNT) values ('C00001','I00001','M00007',3);
Insert into ONECHO.CARTLIST (CARTLIST_NO,ITEM_NO,MEMBER_NO,CARTLIST_COUNT) values ('C00004','I00002','M00007',1);
Insert into ONECHO.CARTLIST (CARTLIST_NO,ITEM_NO,MEMBER_NO,CARTLIST_COUNT) values ('C00002','I00001','M00006',2);
Insert into ONECHO.CARTLIST (CARTLIST_NO,ITEM_NO,MEMBER_NO,CARTLIST_COUNT) values ('C00003','I00002','M00006',2);

REM INSERTING into ONECHO.WISHLIST
SET DEFINE OFF;
Insert into ONECHO.WISHLIST (WISHLIST_NO,ITEM_NO,MEMBER_NO,WISHLIST_MEMO) values ('W00001','I00001','M00007','ì°?!');
Insert into ONECHO.WISHLIST (WISHLIST_NO,ITEM_NO,MEMBER_NO,WISHLIST_MEMO) values ('W00002','I00002','M00006','ì¹œêµ¬? ë¬¼');

REM INSERTING into ONECHO.DELIVERY
SET DEFINE OFF;
Insert into ONECHO.DELIVERY (DELIVERY_CODE,DELIVERY_STATUS) values ('D1','ë°°ì†¡ ??);
Insert into ONECHO.DELIVERY (DELIVERY_CODE,DELIVERY_STATUS) values ('D2','ë°°ì†¡ ì¤?);
Insert into ONECHO.DELIVERY (DELIVERY_CODE,DELIVERY_STATUS) values ('D3','ë°°ì†¡ ?„ë£Œ');

REM INSERTING into ONECHO.PAYMENT
SET DEFINE OFF;
Insert into ONECHO.PAYMENT (PAYMENT_CODE,PAYMENT_STATUS) values ('P1','?…ê¸ˆ ??);
Insert into ONECHO.PAYMENT (PAYMENT_CODE,PAYMENT_STATUS) values ('P2','?…ê¸ˆ ??);

REM INSERTING into ONECHO.STATISTIC
SET DEFINE OFF;
Insert into ONECHO.STATISTIC (STATISTIC_NO,STATISTIC_VISITCOUNT,STATISTIC_TODAYJOIN,STATISTIC_CANCELCOUNT,STATISTIC_MEMBER,STATISTIC_DASK,STATISTIC_IASK,STATISTIC_CASK,STATISTIC_SALES,STATISTIC_DBEFORE,STATISTIC_NEWORDER,STATISTIC_CDATE) 
values ('STA00001',312312,84,10,300000,23,3,7,124123,70,100,to_date('20/06/01','RR/MM/DD'));
Insert into ONECHO.STATISTIC (STATISTIC_NO,STATISTIC_VISITCOUNT,STATISTIC_TODAYJOIN,STATISTIC_CANCELCOUNT,STATISTIC_MEMBER,STATISTIC_DASK,STATISTIC_IASK,STATISTIC_CASK,STATISTIC_SALES,STATISTIC_DBEFORE,STATISTIC_NEWORDER,STATISTIC_CDATE) 
values ('STA00002',100000,77,10,300077,12,8,7,523088,82,120,to_date('20/06/02','RR/MM/DD'));

REM INSERTING into ONECHO.ORDERLIST
SET DEFINE OFF;
Insert into ONECHO.ORDERLIST (ORDER_NO,ITEM_NO,MEMBER_NO,ORDER_DATE,ORDER_COUNT,ORDER_USEPOINT,ORDER_NAME,ORDER_PHONE1,ORDER_PHONE2,ORDER_PHONE3,ORDER_POSTCODE,ORDER_ADDRESS1,ORDER_ADDRESS2,ORDER_REQUEST,ORDER_DCOST,ORDER_CANCELREQUEST,ORDER_CANCELYN,DELIVERY_CODE,PAYMENT_CODE)
values ('O00001','I00001','M00006',to_date('20/06/02','RR/MM/DD'),3,0,'?ê¸¸??,'010','1234','1234','98762','?œìš¸???¡íŒŒêµ?ê°??½ë™ ê°??½ì•„?ŒíŠ¸','110??101??,null,2500,'N','N','D1','P1');
Insert into ONECHO.ORDERLIST (ORDER_NO,ITEM_NO,MEMBER_NO,ORDER_DATE,ORDER_COUNT,ORDER_USEPOINT,ORDER_NAME,ORDER_PHONE1,ORDER_PHONE2,ORDER_PHONE3,ORDER_POSTCODE,ORDER_ADDRESS1,ORDER_ADDRESS2,ORDER_REQUEST,ORDER_DCOST,ORDER_CANCELREQUEST,ORDER_CANCELYN,DELIVERY_CODE,PAYMENT_CODE) 
values ('O00002','I00001','M00007',to_date('20/06/02','RR/MM/DD'),3,0,'?ê¸¸??,'010','1234','1234','98762','?œìš¸???¡íŒŒêµ?ê°??½ë™ ê°??½ì•„?ŒíŠ¸','110??101??,null,2500,'N','N','D1','P1');
Insert into ONECHO.ORDERLIST (ORDER_NO,ITEM_NO,MEMBER_NO,ORDER_DATE,ORDER_COUNT,ORDER_USEPOINT,ORDER_NAME,ORDER_PHONE1,ORDER_PHONE2,ORDER_PHONE3,ORDER_POSTCODE,ORDER_ADDRESS1,ORDER_ADDRESS2,ORDER_REQUEST,ORDER_DCOST,ORDER_CANCELREQUEST,ORDER_CANCELYN,DELIVERY_CODE,PAYMENT_CODE) 
values ('O00003','I00001','M00006',to_date('20/06/02','RR/MM/DD'),1,0,'?ê¸¸??,'010','1234','1234','98762','?œìš¸???¡íŒŒêµ?ê°??½ë™ ê°??½ì•„?ŒíŠ¸','110??101??,null,2500,'N','N','D1','P1');
Insert into ONECHO.ORDERLIST (ORDER_NO,ITEM_NO,MEMBER_NO,ORDER_DATE,ORDER_COUNT,ORDER_USEPOINT,ORDER_NAME,ORDER_PHONE1,ORDER_PHONE2,ORDER_PHONE3,ORDER_POSTCODE,ORDER_ADDRESS1,ORDER_ADDRESS2,ORDER_REQUEST,ORDER_DCOST,ORDER_CANCELREQUEST,ORDER_CANCELYN,DELIVERY_CODE,PAYMENT_CODE) 
values ('O00003','I00002','M00006',to_date('20/06/02','RR/MM/DD'),1,0,'?ê¸¸??,'010','1234','1234','98762','?œìš¸???¡íŒŒêµ?ê°??½ë™ ê°??½ì•„?ŒíŠ¸','110??101??,null,2500,'N','N','D1','P1');

REM INSERTING into ONECHO.REVIEW
SET DEFINE OFF;
Insert into ONECHO.REVIEW (REVIEW_NO,ORDER_NO,ITEM_NO,MEMBER_NO,REVIEW_CDATE,REVIEW_RATE,REVIEW_CONTENT,REVIEW_UDATE,REVIEW_IMAGENAME,REVIEW_IMAGEPATH) 
values ('R00001','O00001','I00001','M00007',to_date('20/06/02','RR/MM/DD'),5,'ì¢‹ì•„ ?„ì£¼ì¢‹ì•„??,to_date('20/06/02','RR/MM/DD'),'ê³ ë¬´?˜ë¬´.jpg','/IMAGES/ITEM/');
Insert into ONECHO.REVIEW (REVIEW_NO,ORDER_NO,ITEM_NO,MEMBER_NO,REVIEW_CDATE,REVIEW_RATE,REVIEW_CONTENT,REVIEW_UDATE,REVIEW_IMAGENAME,REVIEW_IMAGEPATH) 
values ('R00003','O00003','I00001','M00006',to_date('20/06/02','RR/MM/DD'),5,'ê³µê¸°ê°? ?¬ë¼??^^',to_date('20/06/02','RR/MM/DD'),'testsample.jpg','/IMAGES/ITEM/');

REM INSERTING into ONECHO.QNA
SET DEFINE OFF;
Insert into ONECHO.QNA (QNA_NO,MEMBER_NO,QNA_TITLE,QNA_CDATE,QNA_CONTENT,QNA_ANSWER,QNA_CATEGORY,QNA_PASSWORD,QNA_YN, QNA_IMAGENAME, QNA_IMAGEPATH) 
values ('Q00001','M00006','?”ë¶„??? íƒ ê°??¥í•œê°???',to_date('20/06/02','RR/MM/DD'),'?”ë¶„?‰ì´ ê¶ê¸ˆ?´ìš”',null,'?í’ˆ','1234','N','testsample.jpg','/IMAGES/ITEM/');


--- VIEW ADD
-- ì¹´íŠ¸ë¦¬ìŠ¤??ë·?
CREATE OR REPLACE VIEW MEMBER_CARTLIST AS
SELECT CARTLIST_NO, CA.ITEM_NO, ITEM_NAME, ITEM_PRICE, ITEM_MAX, MEMBER_NO, CARTLIST_COUNT, II.IMAGE_NO, IMAGE_NAME
FROM CARTLIST CA
JOIN (
      select I.item_no, itemimage_no, IMAGE_NO, ITEM_NAME, ITEM_PRICE, ITEM_MAX
      from item I
      join (SELECT *
            FROM ITEMIMAGE
            WHERE itemimage_category=1) M on (I.item_no=M.item_no)
      ) II on (CA.item_no=II.item_no)
JOIN IMAGE IM ON (II.IMAGE_NO = IM.IMAGE_NO);

-- ?¤ë” ?•ì¸
CREATE OR REPLACE VIEW ORDERCHK AS
SELECT ORDER_NO, IMAGE_PATH, ITEM_NO, ITEM_NAME, ITEM_MAX, DELIVERY_STATUS
FROM ORDERLIST O
JOIN ITEM IT ON(IT.ITEM_NO = O.ITEM_NO)
JOIN ITEMIMAGE II ON(II.ITEM_NO = IT.ITEM_NO)
JOIN IMAGE IM ON(IM.IMAGE_NO = II.IMAGE_NO)
JOIN DELIVERY D ON(D.DELIVERY_CODE = O.DELIVERY_CODE);
ROLLBACK;

-- ?„ì‹œ ?•ì¸
>>>>>>> refs/remotes/origin/master
CREATE OR REPLACE VIEW WISHCHK AS
SELECT WISHLIST_NO, IMAGE_PATH, ITEM_NAME, WISHLIST_MEMO
FROM WISHLIST W
JOIN ITEM IT ON(IT.ITEM_NO = W.ITEM_NO)
JOIN ITEMIMAGE II ON(II.ITEM_NO = IT.ITEM_NO)
JOIN IMAGE IM ON(IM.IMAGE_NO = II.IMAGE_NO);

CREATE OR REPLACE FORCE VIEW V_ITEMIMAGE ("ITEM_NO", "mItemImgNo", "mainImgNo", "mainImgName", "mainPath", "sItemImgNo", "subImgNo", "subImgName", "subPath") AS 
select I.item_no,M.itemimage_no "mItemImgNo", M.image_no "mainImgNo", M.IMAGE_NAME "mainImgName",M.image_path "mainPath",
        S.itemimage_no "sItemImgNo",S.image_no "subImgNo",S.image_name "subImgName",S.image_path "subPath"
from item I
left join (SELECT IT.ITEM_NO,ITEMIMAGE_NO,IT.IMAGE_NO,IMAGE_NAME,IMAGE_PATH,ITEMIMAGE_CATEGORY
            FROM ITEMIMAGE IT
            left join image G on (IT.IMAGE_NO = G.IMAGE_NO)
            WHERE itemimage_category=1) M on (I.item_no=M.item_no)
left join (SELECT MG.ITEM_NO, ITEMIMAGE_NO, MG.IMAGE_NO,IMAGE_NAME,IMAGE_PATH,ITEMIMAGE_CATEGORY
            FROM ITEMIMAGE MG
            left join image E on (MG.IMAGE_NO = E.IMAGE_NO)
            WHERE itemimage_category=2) S on (I.item_no=S.item_no);

COMMIT;
